### ISSUE TITLE
We need a favicon

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#1]
The logo for the Forum Helpers is a rectangle, but favicons (the little picture which is displayed in the tab) needs to be a square. Would anyone be interested in making a square version of the Forum Helpers logo?

**Comment by NilsTheBest** [comment]
If I recall correctly, the dimensions of a favicon are 64x64, so we can't really do much. I might give it a try.

**Comment by adsuri** [comment]
I'm guessing it'll be initials (FH)?

**Comment by adsuri** [comment]
Would this be good? I think the size is correct.

**Comment by adsuri** [comment]
Whoops Here it is:
http://u.cubeupload.com/adsuri/mqYTKA.png

**Comment by Accio1** [comment]
> Whoops Here it is:
> http://u.cubeupload.com/adsuri/mqYTKA.png

I like that, but I was wondering if we could keep the peace sign from the original logo (the one which is the studio thumbnail), so that it is more recognisable.

**Comment by NilsTheBest** [comment]
![FHthumbnail1](https://user-images.githubusercontent.com/41824646/57584252-3b1d1e00-74d9-11e9-90ec-2a707054f104.png)
Is this ok?

**Comment by adsuri** [comment]
Nice!! I prefer NilsTheBest's one.

**Comment by NilsTheBest** [comment]
Thanks :) I'll try to see how I can improve it and make it more recognizable though.

**Comment by Accio1** [comment]
> I tried.
> ![FHthumbnail1](https://user-images.githubusercontent.com/41824646/57584252-3b1d1e00-74d9-11e9-90ec-2a707054f104.png)
> 
> But this is what we see:
> ![fhthumbnail1(1)](https://user-images.githubusercontent.com/41824646/57584288-aebf2b00-74d9-11e9-8dff-a864386c3a25.png)
> "FH" isn't that visible, we need a better contrast :c

I really like this! To me the FH is visible enough.

**Comment by NilsTheBest** [comment]
I have a hard time seeing it

**Comment by adsuri** [comment]
Try a slightly darker color?

**Comment by NilsTheBest** [comment]
yeah

**Comment by NilsTheBest** [comment]
Much better:
![FHtest3](https://user-images.githubusercontent.com/41824646/57585047-e1215600-74e2-11e9-838a-52a10a836cf2.png)
Favicon:
![fhtest3](https://user-images.githubusercontent.com/41824646/57585063-22196a80-74e3-11e9-9c85-7c5dca2005cc.png)

**Comment by Accio1** [comment]
> Much better:
> ![FHtest3](https://user-images.githubusercontent.com/41824646/57585047-e1215600-74e2-11e9-838a-52a10a836cf2.png)
> 32x32:
> ![fhtest3](https://user-images.githubusercontent.com/41824646/57585063-22196a80-74e3-11e9-9c85-7c5dca2005cc.png)

Great! I like that one! That will be our favicon unless anyone objects.

**Comment by NilsTheBest** [comment]
Nice! I'll improve it later on but we'll stick with this then :)
