### ISSUE TITLE
Forum Helpers List: add curators

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#100]
A checkbox indicates a user has provided a bio.

**Describe the changes needed**
add the following people:

- [x] ninjaMAR
- [x] Futurebot5
- [x] Steve0Greatness
- [ ] ScratchCatHELLO
- [x] mybearworld
- [x] Jeffalo
- [x] dogsmakemehappy
- [x] -EmeraldThunder-
- [x] scratchykit5743
- [x] 9gr
- [ ]  Nezon

**Additional context**
ill do it soon

NOTE: If you are a user on this list please do provide a bio by replying to this issue.

Copy and paste message:

Hello! Congrats on getting accepted to TFH! If you don't mind, could you please provide a bio for our website? You can see some examples here: https://theforumhelpers.github.io/forumhelpers/ Please comment the bio you would like as well as your Scratch user id (find it at api.scratch.mit.edu/users/YOURUSERNAME/) on the following GitHub issue: https://github.com/theforumhelpers/theforumhelpers.github.io/issues/100 If you absolutely can't comment on GitHub, you may reply to this comment. Thanks!

👀  =  i viewed

yo 100 issues/prs

**Comment by FunctionalMetatable** [comment]
sorry for bothering you but I think you need to add scratchykit5743 and 9gr (me as i just joined)

**Comment by leahcimto** [comment]
> sorry for bothering you but I think you need to add scratchykit5743 and 9gr (me as i just joined)

@FunctionalMetatable No worries! I'll add you both to the list now. If you don't mind, could you provide a bio here?

**Comment by FunctionalMetatable** [comment]
> > sorry for bothering you but I think you need to add scratchykit5743 and 9gr (me as i just joined)
> 
> @FunctionalMetatable No worries! I'll add you both to the list now. If you don't mind, could you provide a bio here?

Thanks!

+bio: yeet lol

**Comment by Scratchykit-Iz-Github** [comment]
Okay, so I had to snag myself a GitHub account to do this, so...(I’m @scratchykit5743 on scratch mind you): I’m an autistic, myxophobic tween forumer and furry artist that does her magic primarily in QaS. I’m a part of the Forest cloud multiplayer collab and do pretty much everything but add collabs on the collaborations directory (I co-run the directory, and if you read the posts in that topic you will have proof).

**Comment by Scratchykit-Iz-Github** [comment]
Userid is 39136554.

**Comment by Steve0Greatness** [comment]
UserID:60889474

`Hey there! I'm @Steve0Greatness on Scratch... uh...`

**Comment by jeffalo** [comment]
id: 34018398
hi im jeffalo and i like to make scratch addons websites and tools to make your scratch experience better

**Comment by EmeraldThunder1** [comment]
ID 70349036
Hello, I am -EmeraldThunder- and I have a passion for coding. I am very active on the forums and occasionally on the wiki under my old accounts username.

**Comment by leahcimto** [comment]
Mybearworld's bio and ID:

Hi, I'm mybearworld! I like maths, and I'm at scratch pretty often! Happy foruming! &#x1F43B;"
ID: 61394416

**Comment by leahcimto** [comment]
ninjaMAR's bio and ID:

I'm ninjaMAR, a coder who mainly uses python. I am often found it the Advanced Topics helping people. I enjoy experimenting and I also have 1000+ posts

ID: 35527172

**Comment by leahcimto** [comment]
Futurebot5's bio and ID:

Hi! I got accepted into The Forum Helpers in March 2021. You'll find me most in Suggestions. 

ID: 61883320

**Comment by Accio1** [comment]
@leahcimto TheAdriCoolManDude just submitted their bio on my profile.

ID: 28856568

Bio: Hello, I am Adri, I became a Scratch Forum Helper a few years ago. I am active whenever I can, and I am mainly active in the Suggestions & Things I Am Reading & Making Forums. I help out whenever I can.

**Comment by leahcimto** [comment]
dogsmakemehappy's bio and ID:

ID: 17609915 
Bio: I help out people on the forums, mostly in QaS, but somtimes BaG and suggestions

**Comment by leahcimto** [comment]
k 5 days have passed making pr

**Comment by leahcimto** [comment]
nezon: bio

**Comment by leahcimto** [comment]
Time is up, bios are no longer being accepted here.
