### ISSUE TITLE
Permission to make website.

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#103]
Hello. I somehow got the domain [https://theforumhelpers.glitch.me](https://theforumhelpers.glitch.me), the domain [https://the-forum-helpers.glitch.me](https://the-forum-helpers.glitch.me), and also the domain [https://tfh.glitch.me](https://tfh.glitch.me).

And i am requesting permission to create a website on behalf of The Forum Helpers.
The website i am trying to make is basically a Scratch Statistics visualizer, using data from [https://scratchdb.lefty.one/](https://scratchdb.lefty.one/) to get your scratch statistics and display them for you.

What do you guys think?

**Comment by CodeGuy92** [comment]
Sorry, i meant scratch **forum** statistics.

**Comment by leahcimto** [comment]
@CodeGuy92 So basically like scratchstats.com or shefwerld? I am a bit confused about what is being asked.

**Comment by CodeGuy92** [comment]
I am not asking a question. I am requesting permission to create the website on behalf os The Forum Helpers.

Basically, this website will get your statistics from scratch, and display them for you.
But this isn't a copy of shefwerld, this will have many advanced features such as live post count, or displaying your latest posts, or even showing you your siggy.

**Comment by FunctionalMetatable** [comment]
> I am not asking a question. I am requesting permission to create the website on behalf of The Forum Helpers.
> 
> Basically, this website will get your statistics from scratch, and display them for you.
> But this isn't a copy of shefwerld, this will have many advanced features such as live post count, or displaying your latest posts, or even showing you your siggy.

i could help with this

**Comment by FunctionalMetatable** [comment]
> I am not asking a question. I am requesting permission to create the website on behalf of The Forum Helpers.
> 
> Basically, this website will get your statistics from scratch, and display them for you.
> But this isn't a copy of shefwerld, this will have many advanced features such as live post count, or displaying your latest posts, or even showing you your siggy.

this could be easily integrated with this website though

**Comment by CodeGuy92** [comment]
Eehhhh... it is a lot more complicated, but i guess i'll try to fork the repo and make a PR
Thanks!

**Comment by CodeGuy92** [comment]
Now going to the links will redirect you to the repo

**Comment by Accio1** [comment]
@leahcimto thoughts on this. You can go ahead and create this site if you want to, but I'm unsure about having it incorporated as a part of this site. It seems like more of an independent project similar to shefwerld.

**Comment by leahcimto** [comment]
Agreed.

**Comment by leahcimto** [comment]
@CodeGuy92 Also, (just an idea) you could ask jeffalo or catsunited about this stuff if you want to add it to shefwerld or ocular since the topics seem similar.

**Comment by CodeGuy92** [comment]
Nah, i will make a separate website with log-in system.
