### ISSUE TITLE
Translate this into a Jekyll Style/nuxt page

### ISSUE THREAD

**Issue by FunctionalMetatable** [theforumhelpers/theforumhelpers.github.io#104]
issues relating to C:\\ drives will begone because of localhost

**Comment by Accio1** [comment]
Related to #15
This was decided against because I would prefer for this site to have as little dependencies as possible in order to allow for anyone to work on it locally without having to download additional dependencies.

**Comment by leahcimto** [comment]
@Accio1 Yeah, I'm not too interested in using dependencies for the following reasons:

- People would have to download extra things when contributing, and I know that some people (like me) aren't too interested in downloading things from 3rd party sites.
- I've heard of Jekyll, but have never used it and have zero experience with it. I also don't really see why it's needed for such a simple website like this. Things included in HTML and JS work fine so far.

**Comment by FunctionalMetatable** [comment]
> @Accio1 Yeah, I'm not too interested in using dependencies for the following reasons:
> 
> * People would have to download extra things when contributing, and I know that some people (like me) aren't too interested in downloading things from 3rd party sites.
> * I've heard of Jekyll, but have never used it and have zero experience with it. I also don't really see why it's needed for such a simple website like this. Things included in HTML and JS work fine so far.



> Related to #15
> This was decided against because I would prefer for this site to have as little dependencies as possible in order to allow for anyone to work on it locally without having to download additional dependencies.
> 
> @leahcimto thoughts?

alrighty then

**Comment by FunctionalMetatable** [comment]
reopening because #140 and #141 have risen

**Comment by Accio1** [comment]
As stated before, I'm interested in keeping this repository with as little dependencies as possible so that it is easy for anyone to contribute. Right now, it is easy to download this repository and work on it, but using thigs like nuxt or jekyll would make it significantly more difficult.
