### ISSUE TITLE
Remove LankyBox01 from the contributors page

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#106]
Please delete the account LankyBox01 from https://theforumhelpers.github.io/contributors/
It is my friend's account, i asked him to do stuff for me since i was too lazy to make my own github account.

Instead, use CodeGuy92, which is already on the list.

**Comment by CodeGuy92** [comment]
Also if -accio- sees this, pls also review #105

**Comment by Accio1** [comment]
They opened a PR in this repo, which makes them a contributor. Therefore, they will remain on the page.

**Comment by Accio1** [comment]
Reopening since the account has been deleted and therefore should be removed from the page.

**Comment by CodeGuy92** [comment]
It was deleted before you closed the issue too...

**Comment by Accio1** [comment]
If it was deleted recently then it was likely a caching issue.

**Comment by CodeGuy92** [comment]
Yes, i said that in the previous response issue.
