### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#107]
The thing is, their account is _deleted_

That is why i made the repo.

**Comment by CodeGuy92** [comment]
https://github.com/LankyBox01/

**Comment by CodeGuy92** [comment]
see? Deleted.

**Comment by CodeGuy92** [comment]
@Accio1

**Comment by Accio1** [comment]
1. In the future, please reply to the closed issue instead of making a new one.
2. When I checked before I closed the issue, their account still existed. Now that it has been deleted, I will reopen the issue and it will be updated the next time the credits page is updated.

**Comment by CodeGuy92** [comment]
> 2. When I checked before I closed the issue, their account still existed.

It was probably some cache issues or something; it appeared deleted for me.
