### ISSUE TITLE
In the Curators/Manager JSON, use null instead of "No biography provided"

### ISSUE THREAD

**Issue by FunctionalMetatable** [theforumhelpers/theforumhelpers.github.io#109]
In the curator/manager JSON, use null instead of "No biography provided" and add the "no biography provided" bit if its null into the JS script so we save a bit on size

if you guys want i can make a PR?

**Comment by CodeGuy92** [comment]
Yeah make a pull request. 
It's a lot easier just to set variable "null" to "No biography provided." and set curators' bios to "null" with no quotation marks.

**Comment by FunctionalMetatable** [comment]
@Accio1 can i be assigned?

**Comment by leahcimto** [comment]
@Accio1

**Comment by FunctionalMetatable** [comment]
@Accio1 could I be assigned for this?

**Comment by Accio1** [comment]
This seems unnecessary to be honest. It won't save that much size (about 0.0025MB if I did my math right), and usually the list is updated by copy-pasting existing JSON objects, so typing No Biography Provided vs null isn't much of an issue.

**Comment by gosoccerboy5** [comment]
> This seems unnecessary to be honest. It won't save that much size (about 0.0025MB if I did my math right), and usually the list is updated by copy-pasting existing JSON objects, so typing No Biography Provided vs null isn't much of an issue.

I mean, 9gr (functionmetatable) seems pretty eager to go ahead with this, I think I made a fork that works.. it wouldn't be a hard fix and it would probably make me and 9gr feel a bit better :P

**Comment by gosoccerboy5** [comment]
While we're finding things within the JSON, I'd like to note that on [line 242 of the JSON](https://github.com/theforumhelpers/theforumhelpers.github.io/blob/73c47040bec9afb24d179c16ba0b62c4bbdf8ad3/forumhelpers/curators.json#L242), the format changes from using strings for ID to using numbers for ID.

**Comment by Accio1** [comment]
I'm going to go ahead and close this as wontfix because as of right now, there isn't really a reason for this to be changed. If this changes in the future, then this issue will be referenced.
