### ISSUE TITLE
Change the way that the header and footer is implemented.

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#114]
Right now, the header and footer are embeds, meaning that it is very difficult to make changes to them or resize them, especially getting them to look good on a range of devices. Therefore, a better way to insert the header and footer into each page is needed. One way of doing this, which recently worked well for me on another site is by using JavaScript to insert the HTML directly into the page. The header and footer would be assigned as a variable in a JS file, which then would be loaded on each page and would insert the code into the corresponding part of the page. Since the code would then be a part of the page, it could easily be styled using CSS, and changing the JS file would change the header/footer for each page. This would allow issue #89 to be resolved, and would be a good step towards resolving #64 

@leahcimto thoughts?

**Comment by leahcimto** [comment]
I think that sounds good.

**Comment by gosoccerboy5** [comment]
You could go one step further, and insert favicon, stylesheet, etc with Javascript, like I did. Probably not the best idea, but food for thought
