### ISSUE TITLE
Feature Request: 404 page

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#118]
It would be nice to have a 404 page for this site. I could work on this if that's ok with you (@Accio1).

**Comment by Accio1** [comment]
Yes, feel free to go ahead and work on this. Please include on the page:

- [ ] 404: Page not found text
- [ ] Link to homepage
- [ ] Funni hahas (may I suggest [Taco Wizard](https://github.com/theforumhelpers/theforumhelpers.github.io/blob/nothing-to-see-here/resources/Taco-wizard.svg))

**Comment by leahcimto** [comment]
Alright, I'll make sure I add the funni hahas before everything else as they are main priority.

**Comment by leahcimto** [comment]
@Accio1 #120
