### ISSUE TITLE
Bug: Nav block in the list of forum helpers page has no bottom margin

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#123]
**Describe the bug**
Nav block has no bottom margin in the FH page.
<img width="164" alt="Screen Shot 2021-04-06 at 5 42 58 PM" src="https://user-images.githubusercontent.com/68165163/113782036-8e1ca180-96ff-11eb-8f18-b41035c21521.png">

**To Reproduce**
Go to the list of forum helpers page

**Expected behavior**
there should be a bottom margin

**Browser Information**
n/a

**Additional context**
none

**Comment by Accio1** [comment]
I think this happened here: https://github.com/theforumhelpers/theforumhelpers.github.io/pull/73/files#diff-7fd1b6dcc066b73a18d795f6a23edf4c39d7c8b1b9d1791915f8a04608fa643dR100
Changing the height back to 150px should fix this issue.

**Comment by leahcimto** [comment]
@FunctionalMetatable @Shluffy pinging you in case you want to work on this

**Comment by FunctionalMetatable** [comment]
@leahcimto i'm happy to work on this - so could I please be assigned?

**Comment by Accio1** [comment]
@FunctionalMetatable I've assigned you. Feel free to submit a PR

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable I've assigned you. Feel free to submit a PR

Thanks!

**Comment by leahcimto** [comment]
> @leahcimto i'm happy to work on this - so could I please be assigned?

Looks like Accio1 beat me to it :P
