### ISSUE TITLE
Feature Request: Better Lables

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#125]
My suggestion is to have better labels for better organization.

Here's what the labels would look like:

- `approved` ➡️ `pr - approved` (could be `pr: good to merge` as well)

- `blocked` ➡️ `pr: blocked`

- `bug` ➡️ `type: bug`

- `discussion` ➡️ delete this as we now use the discussion tab

- `documentation` ➡️ `type: documentation`

- `duplicate` ➡️ `status: duplicate`

- `enhancement` ➡️ `type: enhancement`

- `Forum Helpers List` ➡️ `type: Forum Helpers List`

- `good first issue` ➡️  stay the same

- `help wanted` ➡️  stay the same

- `high-prio` ➡️ `triage: high` or `priority: high`

- `invalid` ➡️  `status: invalid`

- `involved` ➡️ `type: involved` (or would that be status?)

- `low-prio` ➡️ `triage: low` or `priority: high`

- `med-prio` ➡️ `triage: medium` or `priority: medium`

- `needs-changes` ➡️ `pr - needs-changes`

- `needs-discussion` ➡️ `status: needs-discussion`

- `needs-info` ➡️ `status: needs-info`

- `question` ➡️ `type: question`

- `reminder` ➡️ `type: reminder`

- `SECURTY` ➡️ `type: SECURTY`

- `unreviewed` ➡️ `pr - needs review`

- `URGENT` ➡️ `triage: URGENT` or `priority: URGENT`

- `user-specific` ➡️ `type: user-specific` (or status)

- `wontfix` ➡️ `status: wontfix`

@Accio1 If you are ok with these changes I could work on this. The colors would stay the same.

@Accio1 thoughts?

**Comment by leahcimto** [comment]
@Accio1 Is this ok with you?

**Comment by Accio1** [comment]
Is this really necessary though? It seems like it would add clutter to the labels and make them longer than they need to be.

**Comment by leahcimto** [comment]
I don't really think it would have too much clutter.[ SA uses it and it looks fine](https://github.com/ScratchAddons/ScratchAddons/issues). [It's also considered good practice on github. ](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)

**Comment by leahcimto** [comment]
@Accio1 Do you have anymore thoughts on this

**Comment by Accio1** [comment]
I still feel as though this might add unneeded complexity, especially with such a small project with ~2 issues a week. However, if you think that this is a better system and that it will make things more organised, then go ahead and implement it.

**Comment by leahcimto** [comment]
> Note to self: Labeler will now have to be updated since label names have changed.

Same with issue templates.
