### ISSUE TITLE
Remove "Be Moist"

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#127]
Can the "Be Moist" message be removed from the footer? It died like a year ago

**Comment by Accio1** [comment]
Basically a duplicate of #93 

Be moist is iconic

**Comment by leahcimto** [comment]
😎 Be moist

**Comment by CodeGuy92** [comment]
Oh.

**Comment by CodeGuy92** [comment]
I will make an extension that removes "Be moist" from your website.

**Comment by Accio1** [comment]
> I will make an extension that removes "Be moist" from your website.

Good to know. Seems like a good use of time

**Comment by Shluffy** [comment]
> I will make an extension that removes "Be moist" from your website.

is it ever worth the time?
