### ISSUE TITLE
Feature Request: An april fools part to the website

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#129]
**Is your feature request related to a problem?**
no, but this would fit with the scratch wiki, as well as scratch

**Describe alternatives you've considered**
N/a

**Additional context**
n/a

**Comment by Accio1** [comment]
@Shluffy I'm not sure what you are suggesting here. We did have an April Fool's version of the site. It has been removed now because it is no longer April Fool's.

**Comment by Shluffy** [comment]
> @Shluffy I'm not sure what you are suggesting here. We did have an April Fool's version of the site. It has been removed now because it is no longer April Fool's.

Ah. didn't notice. Where is the code?

**Comment by leahcimto** [comment]
> > @Shluffy I'm not sure what you are suggesting here. We did have an April Fool's version of the site. It has been removed now because it is no longer April Fool's.
> 
> Ah. didn't notice. Where is the code?

@Shluffy https://github.com/theforumhelpers/theforumhelpers.github.io/tree/nothing-to-see-here

**Comment by Accio1** [comment]
Closing as resolved I guess
