### ISSUE TITLE
License file needed

### ISSUE THREAD

**Issue by bybb** [theforumhelpers/theforumhelpers.github.io#13]
Currently this software is proprietary (all rights reserved) to whoever wrote the initial copy and thus is (by technicality) illegal for anyone to copy / develop upon it themselves. I'd recommend the MIT license to go alongside the ethics of Scratch and MIT.

**Comment by Nambaseking01** [comment]
I was about to say MIT.  ;P You said it

**Comment by Accio1** [comment]
Fixed
