### ISSUE TITLE
Forum Helpers List: bio change for -insanitygames-

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#130]
**Describe the changes needed**
change bio to this: Creative, Innovative, Constructive!

**Additional context**
if anyone would like to work on this feel free to ask and I'll assign you.

**Comment by Shluffy** [comment]
> **Describe the changes needed**
> change bio to this: Creative, Innovative, Constructive!
> 
> **Additional context**
> if anyone would like to work on this feel free to ask and I'll assign you.

i could

**Comment by leahcimto** [comment]
> > **Describe the changes needed**
> > change bio to this: Creative, Innovative, Constructive!
> > **Additional context**
> > if anyone would like to work on this feel free to ask and I'll assign you.
> 
> i could and would want to

@Shluffy Great! I'll assign you to this. Please also do #133 in the same PR.

**Comment by Shluffy** [comment]
> > > **Describe the changes needed**
> > > change bio to this: Creative, Innovative, Constructive!
> > > **Additional context**
> > > if anyone would like to work on this feel free to ask and I'll assign you.
> > 
> > 
> > i could and would want to
> 
> @Shluffy Great! I'll assign you to this. Please also do #133 in the same PR.

perfect, thanks

**Comment by Accio1** [comment]
Resolved by #134
