### ISSUE TITLE
Bug: nav links redirect to this repository's version

### ISSUE THREAD

**Issue by FunctionalMetatable** [theforumhelpers/theforumhelpers.github.io#131]
**Describe the bug**
when you work on this repo locally or on a fork, when you click a nav button it redirects you to this repo's version instead of the local version.

**To Reproduce**
1. download a local version
2. open the homepage
3. press a nav button (not the studio one)
4. it redirects you to this repo's version and not the local version

**Expected behavior**
uses the local version for the nav links instead of this repo's version 

**Browser Information**
n/a

**Comment by Shluffy** [comment]
I have a copy of this repo on my computer and The 404 page redirects to index.html, or the main page. but it seems to be everything else

**Comment by CodeGuy92** [comment]
Yes. this could be fixed by replacing /resources/header.html with this:
```
<link rel="stylesheet" type="text/css" href="stylesheet.css">
<div class="nav_content">
	<a href="https://theforumhelpers.github.io" target="_parent"><img src="icon.png" width="64px" height="64px" class="nav_homeicon"></a>
	<h1 class="nav_title">The Forum Helpers</h1>
	<a href="/forumhelpers" class="nav_button" target="_parent">List Of Forum Helpers</a>
	<a href="https://scratch.mit.edu/studios/3688309/" class="nav_button" target="_blank">Our Scratch Studio</a>
	<a href="/QuickReply/" class="nav_button" target="_parent">QuickReply</a>
</div>
```

**Comment by FunctionalMetatable** [comment]
> Yes. this could be fixed by replacing /resources/header.html with this:
> 
> ```
> <link rel="stylesheet" type="text/css" href="stylesheet.css">
> <div class="nav_content">
> 	<a href="https://theforumhelpers.github.io" target="_parent"><img src="icon.png" width="64px" height="64px" class="nav_homeicon"></a>
> 	<h1 class="nav_title">The Forum Helpers</h1>
> 	<a href="/forumhelpers" class="nav_button" target="_parent">List Of Forum Helpers</a>
> 	<a href="https://scratch.mit.edu/studios/3688309/" class="nav_button" target="_blank">Our Scratch Studio</a>
> 	<a href="/QuickReply/" class="nav_button" target="_parent">QuickReply</a>
> </div>
> ```

won't work because if you work on it locally it will redirect to the main drives directory e.g
If my copy of the repo stayed in
C:/Users/_/repos/theforumhelpers.github.io/
when you press the navbar it will redirect you to the C:/ directory part (because C:/ is the root of the drive).

**Comment by Accio1** [comment]
Blocked right now because it is related to #115

**Comment by leahcimto** [comment]
> > Yes. this could be fixed by replacing /resources/header.html with this:
> > ```
> > <link rel="stylesheet" type="text/css" href="stylesheet.css">
> > <div class="nav_content">
> > 	<a href="https://theforumhelpers.github.io" target="_parent"><img src="icon.png" width="64px" height="64px" class="nav_homeicon"></a>
> > 	<h1 class="nav_title">The Forum Helpers</h1>
> > 	<a href="/forumhelpers" class="nav_button" target="_parent">List Of Forum Helpers</a>
> > 	<a href="https://scratch.mit.edu/studios/3688309/" class="nav_button" target="_blank">Our Scratch Studio</a>
> > 	<a href="/QuickReply/" class="nav_button" target="_parent">QuickReply</a>
> > </div>
> > ```
> 
> won't work because if you work on it locally it will redirect to the main drives directory e.g
> If my copy of the repo stayed in
> C:/Users/_/repos/theforumhelpers.github.io/
> when you press the navbar it will redirect you to the C:/ directory part (because C:/ is the root of the drive).

CR, I tried it with this code.
