### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#135]
**Is your feature request related to a problem?**
No, this is just a fun idea i think would be cool to have.

**Describe alternatives you've considered**
No alternatives thought.

**Additional context**
Dark Mode would be useful for browsing on the forums at night.

**Comment by CodeGuy92** [comment]
Just to be clear, i want a dark mode feature to be added to the site.

**Comment by Accio1** [comment]
I'm tired of issues where the sections aren't filled out completely. The point of issue templates are to provide a guide when submitting issues. Please recreate this or edit it so that the sections are filled or properly.

**Comment by CodeGuy92** [comment]
Done.
e

**Comment by Accio1** [comment]
Thank you. If anyone has any suggestions for a colour scheme for dark mode, feel free to suggest it here.

**Comment by CodeGuy92** [comment]
Could i please be assigned?
I wanna make a pr

**Comment by Accio1** [comment]
Discussion is needed about how this will be implemented and which colour scheme will be used.

**Comment by CodeGuy92** [comment]
#424242
#242424
#141414

Some color stuff

**Comment by Steve0Greatness** [comment]
> #424242
> #242424
> #141414
> 
> Some color stuff

how would those be used? What would be the header? What would be the background? What color would the text be?

**Comment by BarelySmooth** [comment]
> 
> 
> > #424242
> > #242424
> > #141414
> > Some color stuff
> 
> how would those be used? What would be the header? What would be the background? What color would the text be?

I tried experimenting with some color combinations and this one looks fine,

#0D1111 for the header and footer
#FFFFFF for the headings ( the h1, h2, and h3 elements)
#AFAB9E (or #C5C2B6) for other text and
#363B3B for the background of the nav-buttons when they are hovered on.

Here is a preview of the home page with the above color scheme (using #AFAB9E for normal text):

![image](https://user-images.githubusercontent.com/83728060/118405904-f52c5f00-b68a-11eb-82f7-8c3c282c5219.png)

**Comment by Steve0Greatness** [comment]
> > > #424242
> > > #242424
> > > #141414
> > > Some color stuff
> > 
> > 
> > how would those be used? What would be the header? What would be the background? What color would the text be?
> 
> I tried experimenting with some color combinations and this one looks fine,
> 
> #0D1111 for the header and footer
> #FFFFFF for the headings ( the h1, h2, and h3 elements)
> #AFAB9E (or #C5C2B6) for other text and
> #363B3B for the background of the nav-buttons when they are hovered on.
> 
> Here is a preview of the home page with the above color scheme (using #AFAB9E for normal text):
> 
> ![image](https://user-images.githubusercontent.com/83728060/118405904-f52c5f00-b68a-11eb-82f7-8c3c282c5219.png)
thanks.

This might need to use cookies(cause otherwise it's almost useless, like the ability to remove the sections in the forums, i.e. WtS)

**Comment by CodeGuy92** [comment]
the small text could be white too, actually.

**Comment by CodeGuy92** [comment]
Should we also switch the logo to a dark mode version?

**Comment by BarelySmooth** [comment]
> the small text could be white too, actually.

I think white makes it a little hard to distinguish the headings and the text. Alternatively,  #C5C2B6 could be used for the small text (it's brighter). @Accio1 what do you think?



> Should we also switch the logo to a dark mode version?

The logo should be kept the same (for consistency)

**Comment by Steve0Greatness** [comment]
I've started making a fork, you can view it [on replit](https://replit.com/@StevesGreatness/theforumhelpersgithubio)

**Comment by CodeGuy92** [comment]
omg this is soooo cool

**Comment by CodeGuy92** [comment]
underline the "switch theme" & make it pointer, or make it a link (href="javascript:function")

**Comment by gosoccerboy5** [comment]
> _why does draft post it? That's not what everything else does... it's not like in gmail when you save an email as a draft, the receiver person gets it_

You can leave the tab open without posting it, or just wait to make the PR. Your branch will still be there.
> or make it a link (href="javascript:function")

please no, lol. javascript: links are bad

**Comment by Steve0Greatness** [comment]
Here's what a dark mode logo _could_ look like, _if_ we decide we want to change the logo to dark mode.

**Comment by Steve0Greatness** [comment]
Is this issue dead?

**Comment by gosoccerboy5** [comment]
> Is this issue dead?

No, but some of the contributors/members are inactive for a while sometimes

**Comment by Accio1** [comment]
@NilsTheBest do you have the original .svg file of the favicon? It would be easier to change the colours on a .svg than on a .png

**Comment by Steve0Greatness** [comment]
> @NilsTheBest do you have the original .svg file of the favicon? It would be easier to change the colours on a .svg than on a .png

did you put this in the wrong issue, or just @ the wrong person?

**Comment by leahcimto** [comment]
> did you put this in the wrong issue, or just @ the wrong person?

It's in the right place

**Comment by Steve0Greatness** [comment]
> > did you put this in the wrong issue, or just @ the wrong person?
> 
> It's in the right place

ok then...

**Comment by Accio1** [comment]
> > > did you put this in the wrong issue, or just @ the wrong person?
> > 
> > 
> > It's in the right place
> 
> ok then...

NilsTheBest designed the original favicon, so I am pinging them to see if they still have the original .svg file so a dark version can be made.

**Comment by Steve0Greatness** [comment]
> > > > did you put this in the wrong issue, or just @ the wrong person?
> > > 
> > > 
> > > It's in the right place
> > 
> > 
> > ok then...
> 
> NilsTheBest designed the original favicon, so I am pinging them to see if they still have the original .svg file so a dark version can be made.

ah, thanks.

**Comment by Steve0Greatness** [comment]
Here are some questions I have about what to do in dark mode:

1. Should the logo be changed?
2. How long until the cookie should expire?

**Comment by CodeGuy92** [comment]
1. Yes.
2. Make it to the year 9999 so it does not expire.

**Comment by Accio1** [comment]
> Here are some questions I have about what to do in dark mode:
> 
> 1. Should the logo be changed?
> 2. How long until the cookie should expire?

1. Yes, I am waiting to get the .svg logo file so it can be changed.
2. localstorage should be used instead of cookies. They don't expire and work when developing locally.

**Comment by Accio1** [comment]
I'm also going to make a few colour change recommendations based on Material Design's dark mode guidelines.

**Comment by Steve0Greatness** [comment]
> 2\. localstorage should be used instead of cookies. They don't expire and work when developing locally.

I'll try that...

**Comment by Steve0Greatness** [comment]
> I'm also going to make a few colour change recommendations based on Material Design's dark mode guidelines.

ok, sounds good.

**Comment by Steve0Greatness** [comment]
@Accio1, did you get the original svg? If they don't respond, someone can always trace the logo.

**Comment by Steve0Greatness** [comment]
> * Yes.
done, you can test it at https://theforumhelpersgithubio.stevesgreatness.repl.co/

**Comment by Steve0Greatness** [comment]
There's a solution to this, [dark reader](https://darkreader.org/)

**Comment by Accio1** [comment]
I was experimenting a bit with this yesterday, and I don't think we actually need a dark mode icon. Just turning down the saturation on the current icon is enough to make it easier on the eyes, while still preserving most of the original colour. I did the same thing to the Ocular Status colours and people's profile pictures just so that scrolling through the page with a black background isn't so hard on the eyes.

**Comment by CodeGuy92** [comment]
> There's a solution to this, [dark reader](https://darkreader.org/)

![f in the chat bois](https://user-images.githubusercontent.com/79767244/120898386-56fd3a80-c633-11eb-800a-5187f89291a3.PNG)
No. It just makes it worse.

**Comment by Accio1** [comment]
Here is a mockup that I made
![image](https://user-images.githubusercontent.com/48496940/120898553-50ea6800-c5f9-11eb-8e0e-215f1f6786fb.png)

**Comment by Steve0Greatness** [comment]
> > There's a solution to this, [dark reader](https://darkreader.org/)
> 
> No. It just makes it worse.

You haven't adjusted the settings at all... there's no "one size fits all" for dark modes... here's a better version in which I changed the settings to fit the site :)
![Screenshot 2021-06-05 12 52 55 PM](https://user-images.githubusercontent.com/75220768/120903784-0e2a8f00-c5fd-11eb-8772-dc19ac6838e1.png)

**Comment by Steve0Greatness** [comment]
> Here is a mockup that I made
> ![image](https://user-images.githubusercontent.com/48496940/120898553-50ea6800-c5f9-11eb-8e0e-215f1f6786fb.png)

I'll make it in css!

**Comment by Accio1** [comment]
I've already done that. I used CSS variables to switch between light and dark modes instead of creating two separate stylesheets.

**Comment by Steve0Greatness** [comment]
> I've already done that. I used CSS variables to switch between light and dark modes instead of creating two separate stylesheets.

That's a much better way! I'm pretty new to web development 😅

**Comment by Accio1** [comment]
@Steve0Greatness If you don't mind, I'm going to take a shot at implementing this myself. I appreciate the hard work that you put in and I will definitely use your code for inspiration, but since this is such a major feature I want to ensure that it is implemented as effectively as possible. I will tag your for review when I make my PR.

**Comment by Steve0Greatness** [comment]
> @Steve0Greatness If you don't mind, I'm going to take a shot at implementing this myself. I appreciate the hard work that you put in and I will definitely use your code for inspiration, but since this is such a major feature I want to ensure that it is implemented as effectively as possible. I will tag your for review when I make my PR.

I don't mind.

**Comment by NilsTheBest** [comment]
I don't have the original .svg anymore as the file is on my old computer, unless it's still on that website that I made it on.
