### ISSUE TITLE
Bug: mybearworld's user id is incorrect

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#136]
**Describe the bug**
mybearworld's user id is incorrect making the default avatar show.

**To Reproduce**
Go to the list of forum helpers page and scroll down to mybearworld.

**Expected behavior**
You should see their profile pic.

**Browser Information**
n/a

**Comment by Accio1** [comment]
This seems like it could be updated with the next set of bio updates.

**Comment by Shluffy** [comment]
I could do this, and @FunctionalMetatable can probably also do it.

**Comment by leahcimto** [comment]
I'll organize one big issue with all changes that are required with changes to the FH list.
