### ISSUE TITLE
Forum Helpers List: Bio Updates + Promotions + New User

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#140]
**Describe the changes needed**
- [x] Promote BSC, under E=MC3
- [ ] Add PUNNAMOODU to curators
- [x] Change mybearworld user ID (related to #136)
- [x] Austinato bio update - "Hello! I've been on the site for over seven years, and became one of the first managers of TFH. I mainly post on the "Questions about Scratch" and "Requests" forums, and occasionally the "Suggestions" forum as well. As you can tell, I have over 6000 forum posts!"
- [x] wangat bio update - "Hey I'm wangat! Scratch Contributor in the Wiki, forums, SDS, and other areas. 500+ posts. Mostly active in "Questions about Scratch" and "Suggestions"
- [x] Remove futurebot something

**Additional context**
I'll be doing this.

**Comment by Accio1** [comment]
Additionally, Austinato would like their bio updated. You can find the bio here: https://scratch.mit.edu/users/-Accio-/#comments-135250637

**Comment by jeffalo** [comment]
> Additionally, Austinato would like their bio updated. You can find the bio here: [scratch.mit.edu/users/-Accio-/#comments-135250637](https://scratch.mit.edu/users/-Accio-/#comments-135250637)

incase the comment goes away
> Oops, I thought I replied to this a while ago. Here's my bio! "Hello! I've been on the site for over seven years, and became one of the first managers of TFH. I mainly post on the "Questions about Scratch" and "Requests" forums, and occasionally the "Suggestions" forum as well. As you can tell, I have over 6000 forum posts!"

**Comment by leahcimto** [comment]
> > Additionally, Austinato would like their bio updated. You can find the bio here: [scratch.mit.edu/users/-Accio-/#comments-135250637](https://scratch.mit.edu/users/-Accio-/#comments-135250637)
> 
> incase the comment goes away
> 
> > Oops, I thought I replied to this a while ago. Here's my bio! "Hello! I've been on the site for over seven years, and became one of the first managers of TFH. I mainly post on the "Questions about Scratch" and "Requests" forums, and occasionally the "Suggestions" forum as well. As you can tell, I have over 6000 forum posts!"

Thank you!
