### ISSUE TITLE
Feature Request: Add FunctionalMetatable and Shluffy to contributions page

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#143]
**Is your feature request related to a problem?**
No. FunctionalMetatable and Shluffy should be added to the contributions page as they have contributed to this (issues)

**Describe alternatives you've considered**
N/A

**Additional context**
FunctionalMetatable would go after CodeGuy92 and Shluffy would go after MTM828

**Comment by FunctionalMetatable** [comment]
I can be assigned for this if its okay with you guys

**Comment by Accio1** [comment]
> **Additional context**
> FunctionalMetatable would go after CodeGuy92 and Shluffy would go after MTM828

For people that have contributed by committing (not opening issues), they are listed in order of number of commits (according to [this](urhttps://github.com/theforumhelpers/theforumhelpers.github.io/graphs/contributors) page. Therefore, FunctionalMetatable would be after shefwerld, and Shluffy would be after ShadowOfTheFuture.



> I can be assigned for this if its okay with you guys

Sure, go ahead. Just adding the usernames to the array on the contributors page will update the page.

**Comment by leahcimto** [comment]
> For people that have contributed by committing (not opening issues), they are listed in order of number of commits (according to this page. Therefore, FunctionalMetatable would be after shefwerld, and Shluffy would be after ShadowOfTheFuture.
> 
> >

Oops, sorry I totally forgot about their recent PRs :P
