### ISSUE TITLE
Feature Request: Better styling

### ISSUE THREAD

**Issue by gosoccerboy5** [theforumhelpers/theforumhelpers.github.io#148]
I'm personally very glad that there's some CSS on the site. It looks decent. But still, it also looks like a site from the early 2000's or something (I haven't been alive for that many years, but still).

I would like a slightly cleaner design.

Maybe a starting point would be basic stuff, like changing the background color, thinning out the h1/h2 elements, etc. Would it require a total overhaul of the CSS? Maybe.

Not that the site is especially ugly, but the appearance could be a bit better. Agree? Disagree? Share why!

<sub>Honestly, I'm not really sure how this would be carried out, so you can close this if you feel like it.</sub>

**Comment by Shluffy** [comment]
I think that while there are better sites out there, but it looks pretty good and isn't bad.

**Comment by Accio1** [comment]
I tried to design this site in a similar style to Scratch 3.0-friendly without being overly childish. Do you have any specific ideas about what could make the site look more modern?

**Comment by gosoccerboy5** [comment]
> Do you have any specific ideas about what could make the site look more modern?
I'm drawing a blank right now, maybe I should experiment a bit and see what works.

> I think that while there are better sites out there, but it looks pretty good and isn't bad.
You're right. Maybe I shouldn't complain, because it's fine in the first place
