### ISSUE TITLE
Feature Request: Helpful Projects Page

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#149]
**Is your feature request related to a problem?**
No. I found this on the studio comments section and thought it would be a cool idea. The comment said:

it would be cool if someone made a "helpful projects to the forums" section on the tfh website that grabs information from the scratch api from this studio and displays all of the projects on the website like turbowarp. got the idea from turbowarp of course

**Describe alternatives you've considered**
Not sure (none provided by nt149)

**Additional context**
Link to comment: https://scratch.mit.edu/studios/3688309/comments/#comments-144149662

**Comment by Accio1** [comment]
I'm not opposed to this idea in general, but I am opposed to making requests to the Scratch API. As of right now, the Scratch API requires a CORS proxy and there has to be a way to ensure that not too many requests are sent in a short period of time. Therefore, I don't think that it is worth the hassle to do an API request for this. I would not be opposed to doing this idea without API requests though.

**Comment by gosoccerboy5** [comment]
Maybe we could use some static json for the project links and update the json file when a project is added/removed..?

**Comment by Steve0Greatness** [comment]
Mockup?
![img](https://user-images.githubusercontent.com/75220768/120723816-50ca5b00-c487-11eb-8bfc-50d6a2efece2.png)

**Comment by Accio1** [comment]
@Steve0Greatness looks good! I would change it to add some more padding between them, similar to the credits page. Also, should the entire project be embedded, or just the thumbnail so that people can click on them and be directed to the actual project?

**Comment by Steve0Greatness** [comment]
> @Steve0Greatness looks good! I would change it to add some more padding between them, similar to the credits page. Also, should the entire project be embedded, or just the thumbnail so that people can click on them and be directed to the actual project?

it could get laggy with too many project embeds.

**Comment by Accio1** [comment]
> > @Steve0Greatness looks good! I would change it to add some more padding between them, similar to the credits page. Also, should the entire project be embedded, or just the thumbnail so that people can click on them and be directed to the actual project?
> 
> it could get laggy with too many project embeds.

That's what I was thinking too. Sticking to just the thumbnails would probably be best for now.

**Comment by Shluffy** [comment]
Could I be assigned? I would just use the thumbnails with a link under them, and possible make it a scrollable thing rather then a few in a row

**Comment by Shluffy** [comment]
> Could I be assigned? I would just use the thumbnails with a link under them, and possible make it a scrollable thing rather then a few in a row

@Accio1

**Comment by FunctionalMetatable** [comment]
@Shluffy We need to add a bit of styling before adding this to the site.

**Comment by Steve0Greatness** [comment]
I've started working on an improved mockup for this page.

**Comment by DawnRooney27** [comment]
> Mockup? ![img](https://user-images.githubusercontent.com/75220768/120723816-50ca5b00-c487-11eb-8bfc-50d6a2efece2.png) _edit: forgot to change the search bar..._

I support! And when you click the project, it show an embed of the project.

**Comment by leahcimto** [comment]
Hi everyone, I am closing this issue now because I don't think it's a really important thing to add and now there are 50+ projects in the studio and some most of them are not "helpful" at all. If anyone else really wants this though let me know and I'll re-open it.
