### ISSUE TITLE
Forum Helpers List: Move jeffalo to after bluebatstar

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#154]
**Describe the changes needed**
Jeffalo should be moved to after Bluebatstar as they left the studio and rejoined. Change managers.json.

**Additional context**
Feel free to ask to be assigned.

**Comment by FunctionalMetatable** [comment]
I'll do it if you guys don't mind

**Comment by leahcimto** [comment]
@FunctionalMetatable Would you still like to work on this (i got an email for some reason)

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable Would you still like to work on this (i got an email for some reason)

why do i keep deleting my comments anyway

Sure, i'll do it

**Comment by gosoccerboy5** [comment]
Isn't jeffalo already at the end/after Bluebatstar? https://github.com/theforumhelpers/theforumhelpers.github.io/blob/8fcfae0611b156a3b8e00d095a0db6bee93336c3/forumhelpers/managers.json#L338-L350
I must be seeing something wrong..

**Comment by Accio1** [comment]
@gosoccerboy5 good catch! @leahcimto are you seeing jeffalo before Bluebatstar when you load the page?

**Comment by leahcimto** [comment]
> @gosoccerboy5 good catch! @leahcimto are you seeing jeffalo before Bluebatstar when you load the page?

@Accio1 Lol I'm so dumb yes jeffalo is after bluebatstar. Sorry for the confusion
