### ISSUE TITLE
Bug: Austinato has a circle for an ocular status

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#156]
**Describe the bug**
Austinato has a circle for an ocular status. They don't have an ocular status, but a circle is showing.

Screenshot:
<img width="339" alt="Screen Shot 2021-05-06 at 7 41 28 PM" src="https://user-images.githubusercontent.com/68165163/117378277-0f07be00-aea3-11eb-918f-1a73aef62641.png">

**To Reproduce**
1. Go to FH list page
2. Scroll down to Austinato
3. notice they have a circle instead of nothing

**Expected behavior**
They should not have anything there as they don't have an ocular status

**Browser Information**
Mac OS 11, Chrome 90

**Additional context**
None

**Comment by Accio1** [comment]
The circle appears because they have set it as their ocular colour. I think this should be intended in case someone wants to set a colour but not a status.

**Comment by Shluffy** [comment]
> The circle appears because they have set it as their ocular colour. I think this should be intended in case someone wants to set a colour but not a status.

true, but maybe make the circle filled in?

**Comment by gosoccerboy5** [comment]
Does this look OK? Using the background-color css property:
<img width="1150" alt="Screen Shot 2021-05-08 at 12 03 20 PM" src="https://user-images.githubusercontent.com/82768218/117547481-6e75e300-aff5-11eb-89b4-83e90e4c24b5.png">

**Comment by Accio1** [comment]
> Does this look OK? Using the background-color css property:
> <img alt="Screen Shot 2021-05-08 at 12 03 20 PM" width="1150" src="https://user-images.githubusercontent.com/82768218/117547481-6e75e300-aff5-11eb-89b4-83e90e4c24b5.png">
> Tested locally, and it seems to work for every person that has an ocular color but not status.
> [gosoccerboy5/theforumhelpers.github.io/tree/fill-status](https://github.com/gosoccerboy5/theforumhelpers.github.io/tree/fill-status)

I feel like the full length stripe of colour would be a bit jarring to look at. If you could find a way to get it to be just a circle, that would be fantastic!

**Comment by gosoccerboy5** [comment]
> I feel like the full length stripe of colour would be a bit jarring to look at. If you could find a way to get it to be just a circle, that would be fantastic!

<img width="433" alt="Screen Shot 2021-05-08 at 3 03 09 PM" src="https://user-images.githubusercontent.com/82768218/117552001-87d75900-b00e-11eb-83e4-02f32120783c.png">
does that work?

**Comment by Accio1** [comment]
> > I feel like the full length stripe of colour would be a bit jarring to look at. If you could find a way to get it to be just a circle, that would be fantastic!
> 
> <img alt="Screen Shot 2021-05-08 at 3 03 09 PM" width="433" src="https://user-images.githubusercontent.com/82768218/117552001-87d75900-b00e-11eb-83e4-02f32120783c.png">
> 
> @Accio1 does that work?

Perfect! Go ahead and submit a PR!
