### ISSUE TITLE
Feature Request: Find manager/curator

### ISSUE THREAD

**Issue by gosoccerboy5** [theforumhelpers/theforumhelpers.github.io#157]
**Is your feature request related to a problem?**
It would be cool if you could search for a certain manager or curator, because it's a big list to search through.
A small bit of code I've gotten that may help is `document.querySelectorAll("h4")[0].childNodes[0].innerText`.
This could be made with a form element, or separate \<input> and \<button> elements

**Describe alternatives you've considered**
Um, I feel like a search would be the best, I can't think of alternatives

**Additional context**
None

I'm currently working on something for this.

**Comment by Accio1** [comment]
Wouldn't CTRL+F work?

**Comment by gosoccerboy5** [comment]
> Wouldn't CTRL+F work?

I suppose

**Comment by gosoccerboy5** [comment]
I threw something together, the design isn't perfect, but it works. Next step is to figure out how to do all this pull request/fork/git stuff 😅

**Comment by Accio1** [comment]
I took a look at your changes, and I like the concept, but there are a few things that I would change. Namely, the search bar and button should be styled with CSS. I'll take a look at this over the weekend and then tag you when I make a PR.

For future reference, you can make a PR by going to the "Pull Requests" tab, and then pressing the "New Pull Request" button, then pressing the blue "compare across forks" link, then selecting your fork and the branch you want to merge on the right side of the arrow.

**Comment by gosoccerboy5** [comment]
> I took a look at your changes, and I like the concept, but there are a few things that I would change. Namely, the search bar and button should be styled with CSS. I'll take a look at this over the weekend and then tag you when I make a PR.

Understandable, it was kinda late last night and I didn't have much time. You can feel free to make your own changes to it, or just ask me to make some.
> For future reference, you can make a PR by going to the "Pull Requests" tab, and then pressing the "New Pull Request" button, then pressing the blue "compare across forks" link, then selecting your fork and the branch you want to merge on the right side of the arrow.

Ah, ok. Thanks! 🙂

**Comment by leahcimto** [comment]
I think this is a cool idea!

**Comment by gosoccerboy5** [comment]
I can probably make a PR, if you want. I don't have to, if you feel like this is a bad idea or needs fixing
