### ISSUE TITLE
Fix indentation style of CSS.

### ISSUE THREAD

**Issue by bybb** [theforumhelpers/theforumhelpers.github.io#16]
I have never seen an indentation style like this and it makes the CSS incredibly hard to read. In addition you use tabs (`\t`) for indentation globally. Can we agree on 2 characters or 4 characters of ` ` (space) rather than tabs for sake of ease of modification.

If you aren't already, install git locally and use `git push` to upload files modified locally using a sane text editor (I'd recommend Notepad++ for Windows).

**Comment by bybb** [comment]
Personally I'm very fond of 4 character space indentation.

**Comment by Accio1** [comment]
Tabs make more sense to me, and are easier to work with than spaces. You just have to press tab once instead of space 2 or 4 times. The code works fine either way, so changing this isn't necessary.

**Comment by bybb** [comment]
Changing this *is* necessary. Your use of tabs goes against standard programming practises and you shouldn't *have* to be manually indenting anything. Please download Git locally and use a text editor such as Notepad++, Sublime Text, Atom.io, VSCode, or anything that performs automatic indentation.

**Comment by Accio1** [comment]
> Changing this _is_ necessary. Your use of tabs goes against standard programming practises and you shouldn't _have_ to be manually indenting anything. 

Just because most people use spaces, that doesn't mean that using tabs is wrong. [This](https://courses.cs.washington.edu/courses/cse154/17au/styleguide/html-css/spacing-indentation-css.html) website says that "Many developers choose to use 4-space or 2-space indentation" that doesn't mean that other ways are wrong, it just means that spaces are more common.

> Please download Git locally

My computer doesn't support Git

> and use a text editor such as Notepad++, Sublime Text, Atom.io, VSCode, or anything that performs automatic indentation.

My text editor does perform automatic indentation

**Comment by bybb** [comment]
> > Please download Git locally
> 
> My computer doesn't support Git

... what computer are you using that doesn't support Git?

ChromeOS support it via Termux, Windows supports it via GitHub Desktop.

**Comment by Accio1** [comment]
> ChromeOS support it via Termux, Windows supports it via GitHub Desktop.

I can't use either

**Comment by Nambaseking01** [comment]
I personally use Sublime Text, and it's a pretty good text editor. I recommend writing your code there then doing copy and paste if you can't use Git.
