### ISSUE TITLE
Feature Request: Lint all the code

### ISSUE THREAD

**Issue by FunctionalMetatable** [theforumhelpers/theforumhelpers.github.io#161]
**Is your feature request related to a problem?**
the code is kinda messy and needs some linting

**Additional context**
please somebody make a PR that lints all the files

**Comment by leahcimto** [comment]
Someone could make a directory on the wiki tab here?

**Comment by Accio1** [comment]
> Someone could make a directory on the wiki tab here?

I think they mean "lint" as in "clean up". @FunctionalMetatable Could you provide some examples of specifically what code needs linting?

**Comment by leahcimto** [comment]
> > Someone could make a directory on the wiki tab here?
> 
> I think they mean "lint" as in "clean up". @FunctionalMetatable Could you provide some examples of specifically what code needs linting?

Oops sorry

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable Could you provide some examples of specifically what code needs linting?
resources/stylesheet.css

**Comment by gosoccerboy5** [comment]
> > @FunctionalMetatable Could you provide some examples of specifically what code needs linting?
> 
> [resources/stylesheet.css
](https://github.com/theforumhelpers/theforumhelpers.github.io/blob/master/resources/stylesheet.css)

You mean the bad placement of closing curly brackets?
https://github.com/theforumhelpers/theforumhelpers.github.io/blob/c19bc9f6d4af02cdb4daeec1420ff39b8dc39932/resources/stylesheet.css#L4-L7

**Comment by leahcimto** [comment]
> > > @FunctionalMetatable Could you provide some examples of specifically what code needs linting?
> > 
> > 
> > [resources/stylesheet.css
> > ](https://github.com/theforumhelpers/theforumhelpers.github.io/blob/master/resources/stylesheet.css)
> 
> You mean the bad placement of closing curly brackets?
> https://github.com/theforumhelpers/theforumhelpers.github.io/blob/c19bc9f6d4af02cdb4daeec1420ff39b8dc39932/resources/stylesheet.css#L4-L7

@gosoccerboy5 I'll admit that is quite irritating

**Comment by gosoccerboy5** [comment]
@FunctionalMetatable would be easily able to fix this, we should probably assign him, since he made the issue (?)

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable would be easily able to fix this, we should probably assign him, since he made the issue (?)

there could be a prettier workflow
