### ISSUE TITLE
Bug: 404.html needs new header

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#166]
**Describe the bug**
404 page needs new header code

**To Reproduce**
Go to https://theforumhelpers.github.io/404

**Expected behavior**
You should see the header

**Browser Information**
N/A

**Additional context**
None

**Comment by gosoccerboy5** [comment]
All we have to do is remove the embeds and add the script tag

**Comment by gosoccerboy5** [comment]
I have a branch that fixes this

**Comment by Accio1** [comment]
> I have a branch that fixes this

@gosoccerboy5 feel free to submit a PR!
