### ISSUE TITLE
Forum Helpers List: Add Chiroyce and han614698

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#167]
**Describe the changes needed**

Add Chiroyce to list of forum helpers.

User ID: 58524660

Bio: "Hello! I'm Chiroyce, a 13 year old boy from India who joined Scratch on the 25th of March, 2020, as I was bored staying at home and doing nothing. I love making unique projects that test the limits of Scratch to prove that anything is possible. I also love helping around in the forums, especially Bugs and Glitches & Advanced Topics. Outside Scratch, I'm a huge tech fan, I love reading books, playing cricket and programming in Python."

Add han614698 to the list of forum helpers

User ID: 41022482

Bio: "I love foruming and that's all I really do! I have 2000+ posts and make 25+ each day."

gosoccerboy5:

"Hi, I'm gosoccerboy5, a Scratch loving Forum Helper! Outside of that, I love programming in Javascript and playing soccer!

**Additional context**
None

**Comment by gosoccerboy5** [comment]
Would this count as a good first issue?

**Comment by leahcimto** [comment]
> Would this count as a good first issue?

Sure. First let me get a bio from han614698 though.

**Comment by gosoccerboy5** [comment]
Can I add mine? 
```js
"Hi, I'm gosoccerboy5, a Scratch loving Forum Helper! Outside of that, I love programming in Javascript and playing soccer!
```

**Comment by leahcimto** [comment]
Sure!

**Comment by leahcimto** [comment]
@gosoccerboy5 Everyone has a bio and this is now ready to be worked on!

**Comment by leahcimto** [comment]
> > Would this count as a good first issue?
> 
> Sure. First let me get a bio from han614698 though.

@gosoccerboy5 I've assigned you! Let me know if you don't want to do this though.

**Comment by gosoccerboy5** [comment]
I'm fine with it

**Comment by gosoccerboy5** [comment]
what order should they be in? chiroyce => han614698?

**Comment by leahcimto** [comment]
helped_code should be false, and it should be chiroyce then han614698

**Comment by gosoccerboy5** [comment]
Oops. I may or may not have teensy-weensy pressed the auto-format button in vscode, which rearranged a bunch of lines lol. I have HW so just give me a while

**Comment by leahcimto** [comment]
No rush!
