### ISSUE TITLE
White below collaborators in macOs

### ISSUE THREAD

**Issue by Nambaseking01** [theforumhelpers/theforumhelpers.github.io#17]
I'm on a Mac at the moment (I usually use Windows, but today this due to personal reasons) and I don't know why but below the "This website was made by -Accio- (Accio1 on Github) and NilsTheBest (NilsTheBest on Github) on behalf of the Forum Helpers" text box there is a whole lot of unneeded white space. Can someone please fix that? Thanks!

**Comment by Accio1** [comment]
This will be addressed after #20 is merged.

**Comment by Accio1** [comment]
Can you please confirm that this is still happening? I don't see any white space on my version of the site.

I don't use MacOS, so I can't fix this. If it is still happening, please use chrome developer tools to find a solution, and then create a pull request to fix the issue.

**Comment by Accio1** [comment]
> Can you please confirm that this is still happening? I don't see any white space on my version of the site.
> 
> I don't use MacOS, so I can't fix this. If it is still happening, please use chrome developer tools to find a solution, and then create a pull request to fix the issue.

@Nambaseking01

**Comment by Nambaseking01** [comment]
Wait though, I can't use it because my dad has symptoms of (the thing) and I can't use his Mac.

**Comment by Accio1** [comment]
@Nambaseking01 any updates? Are you able to use the Mac now?

**Comment by Nambaseking01** [comment]
i'm able to :) will see tomorrow, because- (no time)

**Comment by Accio1** [comment]
I'm going to close this issue. If this problem is still present, please comment on it, or submit a PR to fix it.

**Comment by Nambaseking01** [comment]
Okay.

**Comment by Nambaseking01** [comment]
It's not white but light-blue, which seems to have fixed it. Feel free to end discussion here.
