### ISSUE TITLE
Typo on /contributors

### ISSUE THREAD

**Issue by gosoccerboy5** [theforumhelpers/theforumhelpers.github.io#177]
Expected appearance:
<img width="672" alt="Screen Shot 2021-05-13 at 2 37 14 PM" src="https://user-images.githubusercontent.com/82768218/118177765-be3f1a80-b3f8-11eb-9b62-3ed61f3d7b18.png">
Actual appearance: 
<img width="658" alt="Screen Shot 2021-05-13 at 2 37 01 PM" src="https://user-images.githubusercontent.com/82768218/118177793-c8611900-b3f8-11eb-9b3c-87ac0dbf1c67.png">

Small typo, ig you can close this if this is too small

**Comment by Accio1** [comment]
Go ahead and submit a fix for this if you'd like!

**Comment by gosoccerboy5** [comment]
wait why is priority high

**Comment by Accio1** [comment]
Spelling errors make the site look unprofessional, and it is a simple fix. High priority but not high severity.

**Comment by gosoccerboy5** [comment]
Oh.
