### ISSUE TITLE
Feature Request: Get rid of drag and select for header home icon

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#180]
**Is your feature request related to a problem?**
No, not really. This suggestion came from #176. I noticed one thing that looked like a really good idea.

When you go to the homepage, notice that you can drag the icon in the header around and select it. On most sites this does not happen, for example, Scratch.

To make this happen, the following code should be added to the css for nav-homeicon:
```css
	user-drag: none;
	user-select: none;
	-moz-user-select: none;
	-webkit-user-drag: none;
	-webkit-user-select: none;
	-ms-user-select: none;
```
**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by gosoccerboy5** [comment]
Is this on desktop? I couldn't reproduce the bug.

**Comment by leahcimto** [comment]
@gosoccerboy5 go to the site and notice that you can select the home icon with your cursor and drag it around the screen

**Comment by gosoccerboy5** [comment]
Weird, I can't replicate. Maybe I should try on a mobile device if I ever get the chance

**Comment by TheColaber** [comment]
In that case, could I create a PR for this? Or just reopen #176 because it includes this change?

**Comment by Accio1** [comment]
@TheColaber go ahead and create a new PR that applies these changes to nav_homeicon
