### ISSUE TITLE
Idle > Pointer

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#187]
Make it so that when the mouse hoves over the "okay" and "leave site" button in the google analytics banner, it turns to a pointer
`cursor: pointer;`

**Comment by Accio1** [comment]
In the future, please use the appropriate [Issue Template](https://github.com/theforumhelpers/theforumhelpers.github.io/issues/new/choose) when opening an issue.

**Comment by CodeGuy92** [comment]
alr

**Comment by CodeGuy92** [comment]
can i be assigned pls

**Comment by gosoccerboy5** [comment]
A general styling across the site is that cursor is default even when hovering over buttons. You should probably change all the other instances of buttons if you would like to do this (there's buttons on QuickReply, along with the curator/manager search bar on the forum helper list)

**Comment by gosoccerboy5** [comment]
However, adding a `button:hover` rule wouldn't hurt as it gives more of an appearance of interactivity.

**Comment by Accio1** [comment]
@CodeGuy92 @gosoccerboy5 would either of you like to be assigned?

**Comment by CodeGuy92** [comment]
Yes me

**Comment by CodeGuy92** [comment]
@acc

**Comment by CodeGuy92** [comment]
@Accio1

**Comment by leahcimto** [comment]
@CodeGuy92 I've assigned you.

/cc @Accio1

**Comment by CodeGuy92** [comment]
k

**Comment by Accio1** [comment]
Please leave issues open until the PR that resolves them has been merged.

**Comment by CodeGuy92** [comment]
you should do some rules issue or something. These rules are unclear lol
