### ISSUE TITLE
Google Analytics Includes Forks

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#190]
As of right now, any data being sent from forks (or any site with the Google Analytics tag that has been added to the header), will send analytics data to the main analytics panel. The newer version has no way to filter this data, so when I look at the data, it is coming from every site that has this tag.

The older version of Analytics does have a filter option but it would take a while to set up, and as far as I know, it is a lot less privacy friendly. (eg. the newer version will take a generalised IP address to get vague location data, whereas the older version takes your entire IP address and gives very specific location data). Therefore, I am opposed to setting up the older analytics to filter the data.

One thing that I think might be possible is adding the Google Analytics tag conditionally using JS, but this would not prevent people from adding it manually. Otherwise, we could just request that people remove the tag when they fork the repo, but that it a hassle and I don't think it is worth the time.

@leahcimto @gosoccerboy5 thoughts?

**Comment by gosoccerboy5** [comment]
I don't know much about this stuff

**Comment by BarelySmooth** [comment]
```window.location.host```
I think using this should work. If it is equal to "theforumhelpers.github.io", then you can append the script tag.

> One thing that I think might be possible is adding the Google Analytics tag conditionally using JS, but this would not prevent people from adding it manually.

Well, in that case, will using a ["Secret"](https://github.com/theforumhelpers/theforumhelpers.github.io/settings/secrets/actions) work? I don't know much about them but I think it should work.

**Comment by gosoccerboy5** [comment]
> `window.location.host`

That's a clever idea

**Comment by leahcimto** [comment]
Kind of like @BarelySmooth said, maybe something like this would work?

```html

<!-- PLEASE DO NOT ALTER THE FOLLOWING CODE IF YOU HAVE FORKED THIS REPOSITORY-->
<script>
if (window.location.hostname === "theforumhelpers.github.io"){
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());
	gtag('config', 'G-FGN5P806VX');
}
</script>
<!--END-->
```

Of course, people could always change it manually though as you said. I'll try to do some research on if it's possible to make something secret in a github repository.

**Comment by BarelySmooth** [comment]
> Kind of like @BarelySmooth said, maybe something like this would work?
> 
> ```
> 
> <script>
> if (window.location.hostname === "theforumhelpers.github.io"){
> 	window.dataLayer = window.dataLayer || [];
> 	function gtag(){dataLayer.push(arguments);}
> 	gtag('js', new Date());
> 	gtag('config', 'G-FGN5P806VX');
> }
> </script>
> 
> ```

Putting it in an if statement would be a good temporary fix until a proper fix can be implemented.

> Of course, people could always change it manually though as you said. I'll try to do some research on if it's possible to make something secret in a GitHub repository.

One solution could be to obfuscate the JS code. There are online tools to do that but I'm not sure how reliable they are.

**Comment by leahcimto** [comment]
> One solution could be to obfuscate the JS code. There are online tools to do that but I'm not sure how reliable they are.

It might be possible to obfusicate the if statment and the things inside it to prevent altering. Here is something I did with https://obfuscator.io/:

```html
<!--DO NOT ALTER THE FOLLOWING CODE-->
<script>
var _0x4e1e=['push','93ZhzVDQ','hostname','84521RXRLDs','17537vmYoIy','location','config','29ZXBpha','120977XeaVia','103iudLQZ','3XqFvZu','1979jIvvJP','625kYTFkr','dataLayer','theforumhelpers.github.io','334bMvhzV','4SDNvbE','1895EuaNBQ'];var _0x4f06cd=_0x2d34;function _0x2d34(_0x2d4a4b,_0x16d94a){_0x2d4a4b=_0x2d4a4b-0xa7;var _0x4e1ef7=_0x4e1e[_0x2d4a4b];return _0x4e1ef7;}(function(_0x58c607,_0xf72366){var _0x26b85b=_0x2d34;while(!![]){try{var _0xd7892a=parseInt(_0x26b85b(0xac))*parseInt(_0x26b85b(0xb4))+parseInt(_0x26b85b(0xb6))+-parseInt(_0x26b85b(0xaa))*parseInt(_0x26b85b(0xb0))+parseInt(_0x26b85b(0xb2))*-parseInt(_0x26b85b(0xa8))+parseInt(_0x26b85b(0xab))*parseInt(_0x26b85b(0xb7))+-parseInt(_0x26b85b(0xb1))*-parseInt(_0x26b85b(0xad))+-parseInt(_0x26b85b(0xa9));if(_0xd7892a===_0xf72366)break;else _0x58c607['push'](_0x58c607['shift']());}catch(_0x47a55b){_0x58c607['push'](_0x58c607['shift']());}}}(_0x4e1e,0x1bac1));if(window[_0x4f06cd(0xb8)][_0x4f06cd(0xb5)]===_0x4f06cd(0xaf)){window['dataLayer']=window[_0x4f06cd(0xae)]||[];function gtag(){var _0x334547=_0x4f06cd;dataLayer[_0x334547(0xb3)](arguments);}gtag('js',new Date()),gtag(_0x4f06cd(0xa7),'G-FGN5P806VX');}
</script>
<!--END-->
```

**Comment by Accio1** [comment]
I've thought it over, and I think I am just going to update the Analytics code to the version that allows you to filter based on domain. I think that conditionally adding it wouldn't work because it is supposed to load as soon as the page does, and conditionally adding it would add it after the page has already loaded. Also, if somebody wanted to be malicious, they could easily fork the repo and reload it a bunch of times to give false data. Additionally, we would have to go back to everybody who has forked the repo and ask them to delete the analytics code. I'll try to get this implemented tonight or tomorrow.

**Comment by BarelySmooth** [comment]
> Additionally, we would have to go back to everybody who has forked the repo and ask them to delete the analytics code. I'll try to get this implemented tonight or tomorrow.

I don't understand. If you will be changing the analytics code to a version that filters based on domain, why would the forks need to remove the analytics code?

**Comment by Accio1** [comment]
> > Additionally, we would have to go back to everybody who has forked the repo and ask them to delete the analytics code. I'll try to get this implemented tonight or tomorrow.
> 
> I don't understand. If you will be changing the analytics code to a version that filters based on domain, why would the forks need to remove the analytics code?

Sorry that I wasn't clear. I was saying that if we were to conditionally add it, we would have to ask them to delete the code. If we change the Google Analytics code then they will not have to delete it since it won't work anymore.
