### ISSUE TITLE
Feature Request: Use consistent element IDs

### ISSUE THREAD

**Issue by FunctionalMetatable** [theforumhelpers/theforumhelpers.github.io#199]
**Is your feature request related to a problem?**
Yes - The ids created by FHP.js are not the nicest looking. They could be
ocular-${user}
instead of
Ocular${user}
**Describe alternatives you've considered**
None

**Additional context**
I could be assigned

**Comment by Accio1** [comment]
I agree. Related to #161. Camel case is best in my opinion for class and ID names.

**Comment by FunctionalMetatable** [comment]
Please could I be assigned?

**Comment by Accio1** [comment]
@FunctionalMetatable Ideally this would be done simultaneously with the fix for #161. Would you like to work on both?

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable Ideally this would be done simultaneously with the fix for #161. Would you like to work on both?

Ok. Can I put them in the same PR?

**Comment by Accio1** [comment]
Yep. Please use tabs instead of spaces, and ensure that class/id names are camelCase
