### ISSUE TITLE
How should the site look?

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#2]
I was thinking that we would have a header with "The Forum Helpers", a small paragraph about us, and then a directory linking to different pages. For example, Forum Helpers and biographies, funny quotes/posts/topics, etc.

Thoughts?

**Comment by NilsTheBest** [comment]
Yeah!
We should keep the same color palette as the thumbnail of the main studio though. I'll give you the hex color codes for the shades of blue that are in the thumbnail if you need them.
In the header, we should have dropdowns with "our members" which would contain little bios about us (e.g. which forums we usually go on, etc.), and some of your suggestions.

**Comment by Accio1** [comment]
Okay! I've started desigining on my own a page for the list of Forum Helpers, and even with very little HTML knowledge, you could help me implement it, as for each user you would just copy and paste some code and change a link to their profile picture.

**Comment by NilsTheBest** [comment]
Gotcha. How would we ask for each forum helper's bio?

**Comment by Accio1** [comment]
Perhaps we could apply some kind of filter to their profile picture once it's in the site, making it slightly grey to signify that they're inactive.

**Comment by NilsTheBest** [comment]
Alright.

For the bios thing, I'm thinking of a menu with every forum helper's logo where when you click on one, you have a little box with their short bio and their logo + username at the top left (or right). Would that be not to hard to make?

**Comment by Accio1** [comment]
That seems like it would be pretty difficult. What would be easier would be having all of them on one page, and then a table of contents which links to the part of the page with that user.

**Comment by NilsTheBest** [comment]
I see. Kind of like on wiki articles where at the beginning there is a summary, and when you click on a link it brings you a certain part of the page?

**Comment by Accio1** [comment]
Yes, very similar to that.

**Comment by NilsTheBest** [comment]
Like this?
![Capture du 2019-05-12 20-26-38](https://user-images.githubusercontent.com/41824646/57586292-4467b400-74f4-11e9-8cc3-012221f3f227.png)

**Comment by Accio1** [comment]
![Screenshot 2019-05-12 at 2 32 50 PM](https://user-images.githubusercontent.com/48496940/57586363-d8b92300-74c2-11e9-93bc-425a3e46287b.png)
This is what I have so far

**Comment by NilsTheBest** [comment]
Ah, yeah! I'm thinking of a better, more readable/enjoyable font. Comfortaa would be a good font for the username. For the content of the bio, I'm thinking of something like Arial or Arimo.

**Comment by Accio1** [comment]
Yes, I just wanted to get the positioning before I start adding fonts or other stuff.

**Comment by NilsTheBest** [comment]
I'm also thinking of a possible "updates" section later on

**Comment by Accio1** [comment]
Like changes to policy and things?

**Comment by Accio1** [comment]
I'm going to create a page for the list of Forum Helpers, so that you can see the code.

**Comment by Accio1** [comment]
Ok, I made this page https://theforumhelpers.github.io/Forum_Helpers/ you can see the code for it here https://github.com/theforumhelpers/theforumhelpers.github.io/blob/master/Forum_Helpers/index.html

**Comment by NilsTheBest** [comment]
> Ok, I made this page https://theforumhelpers.github.io/Forum_Helpers/ you can see the code for it here https://github.com/theforumhelpers/theforumhelpers.github.io/blob/master/Forum_Helpers/index.html

Nice. We also need to define what is inactive and what isn't, so this way we don't have both the active version and inactive version that appear.

**Comment by Accio1** [comment]
I'm thinking if they don't give a biography, they're inactive.

**Comment by NilsTheBest** [comment]
Oh, duh x)

**Comment by Accio1** [comment]
Okay, I'll work on that now.

**Comment by NilsTheBest** [comment]
Sure, it'd go smth like that:
"Hey! I spend most of my time in Questions about Scratch, suggestions, and the french forums. I have recently hit 2.5K posts :') and think I'm addicted to the forums."

**Comment by Accio1** [comment]
For some reason your gif profile picture is way too large, I'm trying to find a fix.

**Comment by NilsTheBest** [comment]
Perhaps use this one? (the one I currently have on github)

**Comment by Accio1** [comment]
I would, but the thing is that lots of people have profile pictures like that, and having them all provide a static image would be a pain.

**Comment by NilsTheBest** [comment]
What's the max logo file size?

**Comment by Accio1** [comment]
I found a fix, implementing now.

**Comment by Accio1** [comment]
Okay, here is what I have so far: https://theforumhelpers.github.io/Forum_Helpers/

**Comment by Accio1** [comment]
Would you like me to start adding more fancy elements, like a header, footer, etc?

**Comment by NilsTheBest** [comment]
Sure :)

**Comment by Accio1** [comment]
Do you have the hex codes for the thumbnail?

**Comment by NilsTheBest** [comment]
Ah, sure. I'll get straight to it.

**Comment by NilsTheBest** [comment]
![Capture du 2019-05-12 22-14-13](https://user-images.githubusercontent.com/41824646/57587304-4f761080-7503-11e9-9b18-0dc83efd6644.png)

**Comment by Accio1** [comment]
Okay, I’ve finished the majority of the nav bar. If you head to the main page ( theforumhelpers.github.io ) and you click on the link for the list page, it should bring you there. Clicking the logo will bring you back to the main page.

**Comment by NilsTheBest** [comment]
Nice! What should be on the main menu? Should it be an explanation on what/who we are?

**Comment by Accio1** [comment]
Yes, that’s what I was thinking. When I get the chance, I’ll add a footer to both pages as well. Do you have any ideas for other pages and/or stuff to put in the footer?

**Comment by NilsTheBest** [comment]
> Do you have any ideas for other pages and/or stuff to put in the footer?

A link to the main studio?

**Comment by Accio1** [comment]
Good Idea, I might even put that in the nav bar/header as well.

**Comment by NilsTheBest** [comment]
Yeah, I'd rather put the link to the main studio in the header too.

**Comment by Accio1** [comment]
Okay, I'll work on that now. Are you online, because if so, I have a small task for you.

**Comment by NilsTheBest** [comment]
Sure? I'm going to bed in like 10 minutes though. Tomorrow morning school starts at 10 am so I might be able to help out ^^

**Comment by Accio1** [comment]
If you want to go through the profiles of the Forum Helpers, and use inspect element to find the link to their profile picture, and paste that with their username somewhere, that would be a big help.

**Comment by NilsTheBest** [comment]
Gotcha. Will do that when I wake up tomorrow morning (cuz it's 0:30 am here right now) since school starts late.

**Comment by Accio1** [comment]
Okay, I might start tonight, so I'll let you know If I have started or not before then.

**Comment by Accio1** [comment]
Nevermind doing that, I did it already. For the footer, I was thinking of having a back to top link, as well as the following sentence(s): "This website was created by -Accio- (Accio1 on Github) and NilsTheBest (NilsTheBest on Github) on behalf of the Forum Helpers."

**Comment by adsuri** [comment]
Just wondering, is there any way I can view what the webpage currently looks like?

**Comment by NilsTheBest** [comment]
> Just wondering, is there any way I can view what the webpage currently looks like?

https://theforumhelpers.github.io/

**Comment by Accio1** [comment]
Would you still like there to be a table of contents with each person, or just Curators and Managers? I think that having a table of contents with each person would make it very long, and therefore a bit unnecessary, but if you want there to be one I would be fine with adding it.

**Comment by NilsTheBest** [comment]
> Would you still like there to be a table of contents with each person, or just Curators and Managers? I think that having a table of contents with each person would make it very long, and therefore a bit unnecessary, but if you want there to be one I would be fine with adding it.

If this is what you were suggesting:
1 - managers
 1.1 - example
 1.2 - exAmple
 1.3 - exampll
2 - curators
 2.1 - someone
 2.2 - someone else
 2.3 - another person

etc.

Support!

**Comment by Accio1** [comment]
Do you want a table of contents which links to the names of every Forum Helper listed on the page. Or one which just links to the manager and curator headings on the page?

**Comment by NilsTheBest** [comment]
If I'm understanding correctly, you want two separate "curators" and "managers" buttons in the header?

**Comment by Accio1** [comment]
No, there will be a table of contents with links to curators and managers. The table of contents won’t be in the header. It will be similar to tables of contents on the wiki.

**Comment by NilsTheBest** [comment]
Oh nvm, I see. XD
Yeah! How do we make a table of contents like that?

**Comment by Accio1** [comment]
It’s not as hard as it seems. You give the headers ids, and then the table of contents is just a div with links to the ids.

**Comment by NilsTheBest** [comment]
Go ahead :P

**Comment by Accio1** [comment]
Ok, do you want to start drafting the about us paragraph which will go on the homepage of the site.

**Comment by NilsTheBest** [comment]
Will get straight to it.

**Comment by NilsTheBest** [comment]
oof sorry for the long wait, I had stuff IRL. How does this sound?

"Hi there! Welcome to The Forum Helpers! We are a small group of people who help around the Scratch forums daily. We mostly help answering questions, give our thoughts on suggestions by scratchers from all over the world, and answer bug reports."

Should I also specify which forums we usually go on and a link to them?

**Comment by Accio1** [comment]
That sounds good. I think links would be a good idea.

**Comment by NilsTheBest** [comment]
ok I'll try reformulating slightly some things and add the links to see how it would look like

**Comment by NilsTheBest** [comment]
Didn't change much, but here we go:

Hi there! Welcome to The Forum Helpers! We are a small group of people who help around the Scratch forums daily. We mostly help answering questions, answer bug reports, give our thoughts on suggestions by scratchers from all over the world.

Suggestions: https://scratch.mit.edu/discuss/1/
Bugs and Glitches: https://scratch.mit.edu/discuss/3/
Questions about Scratch: https://scratch.mit.edu/discuss/4/

**Comment by Accio1** [comment]
Okay, that looks good. Do you have any ideas for anything else to fill the first page, as it has to be large enough to be scroll able, so that the footer will stay at the bottom.

**Comment by NilsTheBest** [comment]
I'll see if I can think of anything

**Comment by NilsTheBest** [comment]
btw I've changed my mind about my bio, do you mind if I change it directly via https://github.com/theforumhelpers/theforumhelpers.github.io/blob/master/Forum_Helpers/index.html ?

**Comment by Accio1** [comment]
Feel free to. I had actually removed your bio, because I thought it was just a rough one for testing. To change it, scroll down to your name, and change "No Biography Provided" to your bio.

**Comment by Accio1** [comment]
Have you thought of anything else to add to the main page. I found a way to get the footer to stay at the bottom, but it looks odd without content which fills the page.

**Comment by Accio1** [comment]
I thought of other things to add, so it's more than a page now. I also added the table of contents to the List of Forum Helpers page, so both pages are basically done, unless you want to add something else to them.

**Comment by NilsTheBest** [comment]
Neat! We also need to change the font to make it look better. I think the background of the main page should also be a bit brighter and welcoming.

**Comment by NilsTheBest** [comment]
oops no that looks back I'm reverting this

**Comment by NilsTheBest** [comment]
FYI, I added ZZ9PluralZAlpha's bio as he requested it :)

**Comment by Accio1** [comment]
> FYI, I added ZZ9PluralZAlpha's bio as he requested it :)

Thanks. The only thing is, in the future can we please wait until we are making another commit, or until lots of people have requested them to be added, so that we're not making commits just to add bios.

**Comment by NilsTheBest** [comment]
> funny quotes/posts/topics, etc.

We need this

There's a quote from @cheddargirl that absolutely needs to be there

**Comment by Accio1** [comment]
Okay, I'll create an "In Development" page where we can work on this.

**Comment by Accio1** [comment]
Another page that I was thinking of adding was a page where there would be frequently posted replies, with buttons to copy each reply to your clipboard. This would make it easier, because you wouldn't have to type out the reply each time, you could just go to the page and copy and paste it.

Thoughts?

**Comment by Accio1** [comment]
This discussion isn't really required anymore.
