### ISSUE TITLE
Feature Request: Use document.createElement instead of pure HTML injection

### ISSUE THREAD

**Issue by FunctionalMetatable** [theforumhelpers/theforumhelpers.github.io#200]
**Is your feature request related to a problem?**
Yes. The injection of pure html in imports.js and FHP.js bugs me. To look a bit professional, we should use document.createElement instead.

**Describe alternatives you've considered**
Linting the JS files and Linting the HTML inside it

**Additional context**
I could be assigned

**Comment by Accio1** [comment]
As of right now, we are not accepting any user-generated content, so using .innerHTML is not an issue because it does not raise any security risks.

**Comment by gosoccerboy5** [comment]
> we should use document.createElement instead.

I don't think @Accio1 wants to spend time using document.createElement for each element, inserting it, bla bla. InnerHTML may be a bit messy but it's easier to write.

**Comment by gosoccerboy5** [comment]
```js
document.createCustomElement = function(type, custom = {}) {
	let temp = document.createElement(type);
	for (let key in custom) {
		temp[key] = custom[key];
	}
	return temp;
};
```
This should streamline the document.createElement process (if you do end up doing this) so you can do things like:
```js
document.createCustomElement("a", {
	href: "https://scratch.mit.edu",
	innerText: "Scratch"
});
```

**Comment by Accio1** [comment]
I'm going to add the wontfix label. There is currently no reason to switch this, so the effort would not be worth it.
