### ISSUE TITLE
Feature Request: Use Vue as a framework (loading it from a JS file)

### ISSUE THREAD

**Issue by FunctionalMetatable** [theforumhelpers/theforumhelpers.github.io#201]
**Is your feature request related to a problem?**
We could get rid of most messy javascript. We could use v-for to iterate over the forum helpers list.

**Additional context**
Vue would make the site easier to maintain

**Comment by FunctionalMetatable** [comment]
This would close #200.

**Comment by Accio1** [comment]
As mentioned [here](https://github.com/theforumhelpers/theforumhelpers.github.io/issues/64#issuecomment-767829408)

"I'd like this site to have as little dependencies as possible so that it is easy for anyone to contribute to."

**Comment by FunctionalMetatable** [comment]
> As mentioned [here](https://github.com/theforumhelpers/theforumhelpers.github.io/issues/64#issuecomment-767829408)
> 
> "I'd like this site to have as little dependencies as possible so that it is easy for anyone to contribute to."

But vue is **just a javascript file**, not a **whole framework** like [nuxt](https://nuxtjs.org)

**Comment by Accio1** [comment]
It is also unfamiliar to many people who might only be familiar with HTML, CSS, and JS.

**Comment by TheColaber** [comment]
Not really... Vue is just javascript, but with convenient features. For instance, you could do something like
```html
<input v-input="inputFunction" />
```
instead of
```html
<input />
```
```js
document.querySelector("input").addEventListener("input", inputFunction)
```

I think the first one looks better. Plus vue is epic for a lot more reasons.

**Comment by Accio1** [comment]
@TheColaber Yes, it is JavaScript, but people who wanted to contribute would have to learn how to use Vue, which might discourage them from contributing.

**Comment by TheColaber** [comment]
Please explain how my post above is too hard to understand and would discourage people from contributing. As if `v-input` in my example was not easy to understand, you could also just take 3 seconds to look at the docs. I mean yes, it is up to you but Vue and React is the standard way to make websites nowadays. Scratch is made from React by the way... There are a lot of companies that use Vue too... Google, apple, zoom, gitlab, etc.

**Comment by Accio1** [comment]
I know Vue. My point is that other people might not, and it could discourage them from contributing. Since this is a community effort, it should be as easy as possible for anyone to work on, and people who are just starting to learn HTML/CSS/JS might be discouraged if they have to read an entire set of documentation just to contribute.

**Comment by jeffalo** [comment]
> people who are just starting to learn HTML/CSS/JS might be discouraged if they have to read an entire set of documentation just to contribute.

but they would be learning, and challenging yourself to learn something new is a good thing isn't it?

**Comment by Shluffy** [comment]
> > people who are just starting to learn HTML/CSS/JS might be discouraged if they have to read an entire set of documentation just to contribute.
> 
> but they would be learning, and challenging yourself to learn something new is a good thing isn't it?

Yes, but maybe they don't want to take the time to try something for the first time. As well as it could take them a few hours to learn it and they might not have that time
