### ISSUE TITLE
Feature Request: Credit Taco Wizard

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#212]
**Is your feature request related to a problem?**
Yes, the taco wizard is used from the Scratch Sprite Library without credit. Credit should be given on the credits page.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
I believe the sprite was made by designerd.

**Comment by Accio1** [comment]
Yes, you could probably add the phrase 
"Taco Wizard image from the Scratch Costume Library"
