### ISSUE TITLE
Update Codeowners

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#215]
Codeowners [Line 2](https://github.com/theforumhelpers/theforumhelpers.github.io/blob/703821874f015dc18c2bae6a390feed52783ce17/.github/CODEOWNERS#L2) and [Line 3](https://github.com/theforumhelpers/theforumhelpers.github.io/blob/703821874f015dc18c2bae6a390feed52783ce17/.github/CODEOWNERS#L3) can be put into one line as `/forumhelpers/*.json @leahcimto`

**Comment by Shluffy** [comment]
although that would include `/forumhelpers/past.json` not just `/forumhelpers/curators.json` and `/forumhelpers/managers.json`, but that still is forum helpers list

**Comment by Shluffy** [comment]
> I don't really see why this change needs to be made though? It works fine as it is, and there aren't hundreds of files being individually assigned, just 2.

No. But this changes the icon from saying lien 2 and line 3 and also would include past.json

**Comment by Steve0Greatness** [comment]
What's even the purpose of Codeowners?

**Comment by Shluffy** [comment]
> What's even the purpose of Codeowners?

to automatically request the review of a user if they are a codeowner. see pr #191 and #184

**Comment by Accio1** [comment]
I don't really think that this change is needed. It doesn't have much of an impact, no matter which way you do it. If hundreds of files had to be assigned, then this would obviously be more efficient, but since it is only two, I don't think changing this would even be worth the time.
