### ISSUE TITLE
Feature Request: Actually Make `CONTIRBUTING.md` (contrib guidelines)

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#217]
The branch that it is currently being made on is not used. Would I be able to make it and you guys will just request changes for things that should be removed, changed, added, etc.

**Comment by Accio1** [comment]
@leahcimto is working on this. Just because the branch doesn't have any recent changes doesn't mean that it isn't being developed.

**Comment by leahcimto** [comment]
Yeah, sorry I've been busy should be able to finish this soon now that summer vacation has started for me.
