### ISSUE TITLE
Feature Request: Make Switch Theme a button instead of a link

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#220]
**Is your feature request related to a problem?**
No. I just want the "Switch theme" link to be turned into a button and added into the navbar instead of the footer

**Describe alternatives you've considered**
j

**Additional context**
No additional context.

**Comment by Steve0Greatness** [comment]
This would be a good idea to put into the [pull request](https://github.com/theforumhelpers/theforumhelpers.github.io/pull/208).

**Comment by Accio1** [comment]
I'd prefer that it remains in the footer, but I agree that it should be a button. Also, in the future, fill out the issue template properly or it will be closed.

**Comment by Accio1** [comment]
Closed in #226
