### ISSUE TITLE
Use Actions for stale issues

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#224]
Currently there is one stale issue with the stale label (`status: stale`). #121. leahcimto manually added it after about a month and a half. This would mark it as stale after a certain amount of time (you can specify for issue and pr separately) and then can specify how many days until close. You can use labels and milestones to exempt stuff, etc.

**Helpful Links:**
[An example of this in use](https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/blob/master/.github/workflows/actions-stale.yml)
[Stale on the github market place](https://github.com/marketplace/actions/close-stale-issues)
[3rd party app you could use instead (probot)](https://github.com/marketplace/stale) Although I find the one by actions can be configured pretty easily, unlike the one bu probot

**Comment by Accio1** [comment]
We tried having an auto labeller in the past and it worked very poorly.

**Comment by Shluffy** [comment]
> We tried having an auto labeller in the past and it worked very poorly.

You could try probot. Just actions one is easier to configure and has more options

**Comment by gosoccerboy5** [comment]
Not that many issues go stale (not that many exist (for very long until they're resolved)), so manually adding the label is fine.

**Comment by leahcimto** [comment]
> Not that many issues go stale (not that many exist (for very long until they're resolved)), so manually adding the label is fine.

+1

**Comment by Shluffy** [comment]
I guess this is what this is coming to. I am gonna close this
