### ISSUE TITLE
Forum Helpers List: New Users

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#227]
**Describe the changes needed**

A checkmark means a bio has been provided.

Add the following users to curators list:

- [x] DarthVader4Life

- [x] #254

- [x] linearlemur

- [ ] potatophant

- [ ] Maximouse

Other:

- [x] Change leahcimto's bio
- [x] Change dogsmakemehappy's bio
- [x] Change -Accio-'s bio

**Additional context**
I can do this and will have a pr up by the end of the week.

**Comment by Shluffy** [comment]
Can you change my bio: `I am not really active on the forums anymore (except for the ATs) and I am mostly on github as shluffy. <i><b>Coding On github</b></i>`

**Comment by Accio1** [comment]
Please also change my bio to "Hi there! I'm [at-symbol]-Accio-! I am a Forum Helper with 1000+ posts and the former owner of two stickies. I am also an SDS curator, and I enjoy science and math. The forums which I visit most often are Suggestions, Questions About Scratch, and Advanced Topics. Additionally, I am a lead developer on the site you are viewing right now!"

**Comment by linearlemur** [comment]
Set my bio to "I'm a human being obsessed with science, coding, math, history, geography, and linguistics. I'm mostly active in Suggestions, Questions About Scratch, and Advanced Topics."

**Comment by gosoccerboy5** [comment]
I think @ninjaMAR needs a bio update: #244

**Comment by ninjamar** [comment]
Please change my bio to "I'm ninjaMAR, a coder who mainly uses python. I am often found it the Advanced Topics helping people. <h1>test plz ignore</h1>"

**Comment by leahcimto** [comment]
@ninjamar The html tags will not be included.

**Comment by ninjamar** [comment]
> @ninjamar The html tags will not be included.

Oh

**Comment by leahcimto** [comment]
PR up
