### ISSUE TITLE
Feature Request: Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by BarelySmooth** [theforumhelpers/theforumhelpers.github.io#229]
**Is your feature request related to a problem?**
Yes, it should be easier for users to understand the steps to contribute to the repository.

**Describe alternatives you've considered**
An alternative is to add it to the README iteself.

**Additional context**
For example, a new user might not know that you have to wait to be assigned to submit a PR (some repositories allow small changes without being assigned). Its a good practice to have such a file that lays out what contributors must follow. 

Related to #53

**Comment by Shluffy** [comment]
See #217. leahcimto should be working on it [here](https://github.com/theforumhelpers/theforumhelpers.github.io/tree/contributing-guidelines)

**Comment by leahcimto** [comment]
Yep, the pull request should be up now.

**Comment by BarelySmooth** [comment]
> Yep, the pull request should be up now.

Great! (I thought I searched for closed issues too and that didn't show up)
