### ISSUE TITLE
[Labels/milestones] add a backlog label/milestone

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#235]
As of ~~writing~~ typing this there are 9 open isssues. Only 1 is in-progress (maybe #227 should also be), and some are just low priority. Maybe create a backlog label/milestone and anyone can submit a fix for something on the backlog. This would require a change to the contrib guidelines

**Comment by Shluffy** [comment]
this might be documentation?

**Comment by Accio1** [comment]
I am against the idea of anyone being able to submit fixes for old issues. Several of these are marked as needs discussion, which means that it hasn't been completely worked out how to be added yet. People asking to be assigned ensures that there is adequate discussion on each issue before it is implemented.

**Comment by Shluffy** [comment]
> I am against the idea of anyone being able to submit fixes for old issues. Several of these are marked as needs discussion, which means that it hasn't been completely worked out how to be added yet. People asking to be assigned ensures that there is adequate discussion on each issue before it is implemented.

but u choose which is backlog, for anyone to do

**Comment by Accio1** [comment]
> > I am against the idea of anyone being able to submit fixes for old issues. Several of these are marked as needs discussion, which means that it hasn't been completely worked out how to be added yet. People asking to be assigned ensures that there is adequate discussion on each issue before it is implemented.
> 
> but u choose which is backlog, for anyone to do

Then I likely wouldn't end up choosing any, which wouldn't be helpful.

**Comment by Shluffy** [comment]
ok

**Comment by leahcimto** [comment]
For the future, the help-wanted tag could work.
