### ISSUE TITLE
Bug: Header doesn't work sometimes on mobile

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#236]
**Describe the bug**
The expandable buttons in the header do not expand for some reason on some mobile devices. Clicking on the button that should expand them does nothing

**To Reproduce**
Visit the site on mobile and click the expandable dropdown. On some devices it will not expand.

**Expected behavior**
The dropdown should expand on all devices

**Browser Information**
iOS Safari

**Additional context**
High priority because it affects an entire set of site visitors and impedes them from visiting the List of Forum Helpers page.

**Comment by leahcimto** [comment]
Can reproduce on iPhone safari

**Comment by Accio1** [comment]
I think it will probably have to be worked around using JS onclick, because it seems like CSS :hover doesn't work as intended.

**Comment by BarelySmooth** [comment]
I think its a problem with how Safari handles ```:hover```. [See the compatibility notes on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover#browser_compatibility)

**Comment by Accio1** [comment]
> I think its a problem with how Safari handles `:hover`. [See the compatibility notes on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover#browser_compatibility)

Thanks, I'll take a look

**Comment by Accio1** [comment]
I'll get to work on this tomorrow.
