### ISSUE TITLE
nothing to see here..

### ISSUE THREAD

**Issue by gosoccerboy5** [theforumhelpers/theforumhelpers.github.io#237]
will we delete the branch "nothing-to-see-here" or keep it for next year? we will definitely have to do a bit of fetch and merge and fixing merge conflicts if we want to keep it.

**Comment by BarelySmooth** [comment]
But what is it?

If its some special AFD page, we can easily change the branch from where GitHub Pages builds the website in the repository settings!
From: ***@***.***>
Sent: 13 June 2021 09:19 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [theforumhelpers/theforumhelpers.github.io] nothing to see here.. (#237)


will we delete the branch "nothing-to-see-here" or keep it for next year? we will definitely have to do a bit of fetch and merge and fixing merge conflicts if we want to keep it.

**Comment by Shluffy** [comment]
> But what is it? If its some special AFD page, we can easily change the branch from where GitHub Pages builds the website in the repository settings!

af 2021 archive. we will probably make a new one for 2022

**Comment by Accio1** [comment]
As others have stated, this was the branch for AFD 2021. It was saved for archival purposes. Next year a new branch will be created, since the changes from last year weren't anything that would be too difficult to implement again.

**Comment by Shluffy** [comment]
> As others have stated, this was the branch for AFD 2021. It was saved for archival purposes. Next year a new branch will be created, since the changes from last year weren't anything that would be too difficult to implement again.

are we going to do the same thing as last year? maybe have it be different and possibly allow anyone to make a pr for that branch

**Comment by Accio1** [comment]
> > As others have stated, this was the branch for AFD 2021. It was saved for archival purposes. Next year a new branch will be created, since the changes from last year weren't anything that would be too difficult to implement again.
> 
> are we going to do the same thing as last year? maybe have it be different and possibly allow anyone to make a pr for that branch

AFD 2022 still isn't for another 10ish months, so how about we continue this discussion closer to that time.

**Comment by gosoccerboy5** [comment]
> this was the branch for AFD 2021

I knew that. Thanks for the other info though.
