### ISSUE TITLE
Feature Request: Add outline to contributors pfps

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#252]
**Is your feature request related to a problem?**
No. I want an outline to be added for all of the contributors' pfps in [The Forum Helpers Page](https://theforumhelpers.github.io/forumhelpers/) and the [Contributors](https://theforumhelpers.github.io/contributors/).

**Describe alternatives you've considered**
None.

**Additional context**
Make sure the outline color is updated if the theme is changed, so it fits [these new themes](https://github.com/theforumhelpers/theforumhelpers.github.io/pull/243) too. (You can actually just make the outline color match the color of the pfp if you want, idc)

**Comment by leahcimto** [comment]
How thick would the outline be? What colors would they be matching with each theme?

**Comment by CodeGuy92** [comment]
> How thick would the outline be? What colors would they be matching with each theme?

Honestly, i don't care. You can actually just make the outline color match the color of the pfp.

**Comment by markverb1** [comment]
> > How thick would the outline be? What colors would they be matching with each theme?
> 
> Honestly, i don't care. You can actually just make the outline color match the color of the pfp.

is this good? 
![image](https://user-images.githubusercontent.com/77983517/122967372-115ea280-d393-11eb-98ef-49ca399a7f16.png)

**Comment by Accio1** [comment]
Specifically why do you think outlines are needed?

**Comment by CodeGuy92** [comment]
> @CodeGuy92 Specifically why do you think outlines are needed?

Because it would look better, and also, why not?

**Comment by CodeGuy92** [comment]
> > > How thick would the outline be? What colors would they be matching with each theme?
> > 
> > 
> > Honestly, i don't care. You can actually just make the outline color match the color of the pfp.
> 
> is this good?
> ![image](https://user-images.githubusercontent.com/77983517/122967372-115ea280-d393-11eb-98ef-49ca399a7f16.png)

`border-radius: 5px;`

**Comment by Accio1** [comment]
> > @CodeGuy92 Specifically why do you think outlines are needed?
> 
> Because it would look better, and also, why not?

I think that it would look better without a border. That way, people with .png profile pictures won't have a border that looks like it is going around nothing.

**Comment by CodeGuy92** [comment]
~That would look cooler~ ok
