### ISSUE TITLE
inconsistent indentation

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#255]
https://github.com/theforumhelpers/theforumhelpers.github.io/blob/e849ebda3cbc306e8cf3b7bdccd5782da5954c4f/resources/stylesheet.css#L18-L53
Again, should this be addressed in a new issue? Anyways, this indentation is inconsistent and rather hurts my eyes. I guess you could get away with it because it's CSS and doesn't require multiple indentation levels, but still, I feel like it should be fixed eventually
 - mixing tabs/spaces
 - the second rule has 4 space indentation
 - the third rule has no indentation(!)

_Originally posted by @gosoccerboy5 in https://github.com/theforumhelpers/theforumhelpers.github.io/issues/243#issuecomment-869181201_

**Comment by Accio1** [comment]
@Shluffy it is your PR that adds this indentation issue. Feel free to make another commit to fix it.

**Comment by Shluffy** [comment]
Possible Labels: `type: themes`, `type: enhancement`, `type: dev-facing`, `type: styling`, Maybe `status: needs-discussion`
Okay.
Also this should be in progress then

**Comment by Accio1** [comment]
I'm closing this because it is relating to code that hasn't been committed yet.
