### ISSUE TITLE
Feature Request: fuzzy search at /forumhelpers

### ISSUE THREAD

**Issue by jeffalo** [theforumhelpers/theforumhelpers.github.io#257]
**Is your feature request related to a problem?**
the search bar doesn't do what you expect it to do. it would be neat if it filtered out the list of forum helpers to match your query. a neat way to do this would be fuzzy search, like [fusejs](https://fusejs.io/). you can use some JS to set `display: none;` when a user does not match the search.

**Describe alternatives you've considered**
removing the search bar altogether.. i don't understand how it's useful when crtl+f in the browser can do better.

**Comment by Accio1** [comment]
Similar to what [scratchstats.com](https://scratchstats.com/) does for their search bar?

**Comment by jeffalo** [comment]
> Similar to what [scratchstats.com](https://scratchstats.com/) does for their search bar?

yeah, except searching in the curator list will hide all users who don't match the query.

**Comment by gosoccerboy5** [comment]
I would support an `onchange` or `oninput` event so the user doesn't have to press the button if this were implemented.
