### ISSUE TITLE
Feature Request: transitions for buttons

### ISSUE THREAD

**Issue by LankyBox01** [theforumhelpers/theforumhelpers.github.io#258]
**Is your feature request related to a problem?**
No. I would like a transition to the background color change when a button is being hovered on. Just a little change.
`transition: 2s;`

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Please assign me.

**Comment by Accio1** [comment]
2s is too long. Something along the lines of 0.5 seconds would be better. Feel free to work on this @CodeGuy92

**Comment by gosoccerboy5** [comment]
Hmm, what about a CSS variable for hover transitions?
We could add (or add on to) a CSS rule for `:root`, add a variable like `--hover-transition`, and use that variable in both button hover and link hover.

That, or we could add a specific rule for both links and buttons
```css
a, button {
    transition-duration: 0.4s;
}
```

That way, we can update both at the same time and maintain consistency.

**Comment by CodeGuy92** [comment]
o i got assigned ok ill work
