### ISSUE TITLE
Bug: QuickReply doesn't use themes

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#263]
**Describe the bug**
QuickReply doesn't use themes. I have the scratch theme on, and it's not showing up.
https://theforumhelpers.github.io/QuickReply/

**To Reproduce**
No.

**Expected behavior**
It should be using themes.

**Browser Information**
Why do i need to enter this, it's no use.

**Additional context**
No.

**Comment by Accio1** [comment]
This is currently by design pending QuickReply overhaul.

**Comment by Accio1** [comment]
Also, in the future, please open issues involving QuickReply in the [QuickReply repository](https://github.com/theforumhelpers/QuickReply).
