### ISSUE TITLE
Application Information Page

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#264]
**Is your feature request related to a problem?**
Yes.
Studio managers can no longer change the description of the studio. This means that any future updates to application process, grading process, etc. will not be able to be put in the studio description. Before this change, we updated the description to point to the site, meaning that users wanting to join TFH will be directed here. I think that we should have a separate page for application information, as well as a clear announcement on the main page to direct users there.

**Describe alternatives you've considered**
Honestly, the abruptness of this change means that there wasn't much time for discussion, and this was the best we could come up with in 2 hours. If anyone has a better suggestion, feel free to share.

Applications should probably be closed until this is sorted out.

**Comment by BarelySmooth** [comment]
We might still be able to edit the description for a short while. But we can't guarantee that it won't end up breaking anything.

**Comment by leahcimto** [comment]
> Managers might still be able to edit the description [for a short while](https://uploads.scratch.mit.edu/studios/3688309/comments/). But we can't be sure that it won't end up breaking anything.

I tried, it isn’t possible.


Where will other things go like pending applicants?

**Comment by BarelySmooth** [comment]
> > Managers might still be able to edit the description [for a short while](https://uploads.scratch.mit.edu/studios/3688309/comments/). But we can't be sure that it won't end up breaking anything.
> 
> I tried, it isn’t possible.
> 
> Where will other things go like pending applicants?

Uploads take a long time to update so I guess we should wait a little. What did you try changing?

**Comment by Accio1** [comment]
@BarelySmooth That is a hacky method that surely will be patched soon.

@leahcimto As for pending applicants, I have an idea in mind but I don't want to share it just yet because I'm not sure if it's actually possible. I would recommend that we just close applications for now. Hopefully after things settle down and people have time to think of solutions, we can make a plan to go forward.

**Comment by BarelySmooth** [comment]
> @BarelySmooth That is a hacky method that surely will be patched soon.

Unfortunately, that doesn't work. Backend changes were made to prevent that (or maybe they didn't change it). There is no way we can edit the description again without the studio creator.

**Comment by gosoccerboy5** [comment]
Should we create a new page outlining the application process? The main page should have simple instructions but otherwise link to the applications page for "further information"

**Comment by CodeGuy92** [comment]
I have an idea. Let's just make a new studio where users comment their applications, and i (or someone else) can code an automatic system using the Scratch API to get the latest comments and display them in a secret admin page.
![Capture](https://user-images.githubusercontent.com/79767244/124769918-8f4dac80-df42-11eb-9745-ae54cfc40c0e.PNG)
Then, if an admin clicks reject, the application zaps. If it is accepted, a scratch account (preferably one called @TFH-Apps) will automatically invite the user to the studio using an NPM module called scratch-api, then leave a comment on their profile saying something like "Your TFH application was accepted, please accept the invite."

**Comment by CodeGuy92** [comment]
And the entire application proccess could be automated like this.

**Comment by BarelySmooth** [comment]
@CodeGuy92 I don't understand how this is possible without a backend

**Comment by BarelySmooth** [comment]
@Accio1 I think the third paragraph on the front page should be changed to something like this:

### I'm interested in becoming a Forum Helper! How do I apply?
We're glad that you're interested in applying! We are always on the lookout for new members! However, there are a few requirements that you must fulfill in order to be invited. You can learn more about them [here](https://theforumhelpers.github.io/apply)'

(the wording should probably be modified after discussing in the studio. This is only to give an idea of how it should look like).

**Comment by gosoccerboy5** [comment]
@CodeGuy92 Fetching comments from the API alone would require some sort of CORS proxy or something, but people being able to automatically zap or accept applications would be way to difficult.

**Comment by CodeGuy92** [comment]
> @CodeGuy92 Fetching comments from the API alone would require some sort of CORS proxy or something, but people being able to automatically zap or accept applications would be way to difficult.

> @CodeGuy92 I don't understand how this is possible without a backend

I can make a back-end server on repl.it. This page will only be public to website admins, not users, so i see no reason to do it on github.

**Comment by CodeGuy92** [comment]
> @CodeGuy92 Fetching comments from the API alone would require some sort of CORS proxy or something, but people being able to automatically zap or accept applications would be way to difficult.

I'm already working on this lol

**Comment by Accio1** [comment]
@CodeGuy92 keep in mind that even if you do work on this, there is no guarantee that it will be accepted since you haven't been assigned.

**Comment by CodeGuy92** [comment]
I know. But could you please assign me then?

**Comment by BarelySmooth** [comment]
> > @CodeGuy92 Fetching comments from the API alone would require some sort of CORS proxy or something, but people being able to automatically zap or accept applications would be way to difficult.
> 
> > @CodeGuy92 I don't understand how this is possible without a backend
> 
> I can make a back-end server on repl.it. This page will only be public to website admins, not users, so i see no reason to do it on github.

You'll need an account to invite people. Only managers can do that. But due to the new limits, new managers can't be promoted. You will need to use a script to control an existing manager account. This is not allowed on Scratch.

**Comment by CodeGuy92** [comment]
> > > @CodeGuy92 Fetching comments from the API alone would require some sort of CORS proxy or something, but people being able to automatically zap or accept applications would be way to difficult.
> > 
> > 
> > > @CodeGuy92 I don't understand how this is possible without a backend
> > 
> > 
> > I can make a back-end server on repl.it. This page will only be public to website admins, not users, so i see no reason to do it on github.
> 
> You'll need an account to invite people. Only managers can do that. But due to the new limits, new managers can't be promoted. You will need to use a script to control an existing manager account. This is not allowed on Scratch.

Oh, i just realized that. But that's ok. A manager could firstly accept the application on the website, and then invite the user manually.

**Comment by Scratchykit-Iz-Github** [comment]
I’m considering an alternative, that being an application project. Via this method people who can’t access GitHub will be still able to apply, without parental controls issues.

**Comment by CodeGuy92** [comment]
> I’m considering an alternative, that being an application project. Via this method people who can’t access GitHub will be still able to apply, without parental controls issues.

Bro, that's the best idea ever. Maybe i could combine it with my alternative and people can submit thier applications using cloud instead of a comment.

**Comment by Scratchykit-Iz-Github** [comment]
> > I’m considering an alternative, that being an application project. Via this method people who can’t access GitHub will be still able to apply, without parental controls issues.
> 
> Bro, that's the best idea ever. Maybe i could combine it with my alternative and people can submit thier applications using cloud instead of a comment.

That would be nice, but what would the others think?

**Comment by CodeGuy92** [comment]
> > > I’m considering an alternative, that being an application project. Via this method people who can’t access GitHub will be still able to apply, without parental controls issues.
> > 
> > 
> > Bro, that's the best idea ever. Maybe i could combine it with my alternative and people can submit thier applications using cloud instead of a comment.
> 
> That would be nice, but what would the others think?

idk

Anyways, here's my mockup (that works)
```
var Scratch = require('scratch-api');
const fetch = require('node-fetch');
var express = require('express')
var app = express()

app.get('/accept', function (req, res) {
  Scratch.UserSession.load(function(err, user) {
  user.addComment({"user":"LankyBox01","content":"Hello! Your application for The Forum Helpers was accepted. You will be invited shortly."}, function (err) {
      if(err) return console.error(err);
});
});
res.send(`<meta http-equiv="refresh" content="0;URL='/'" />`)
})

app.get('/', function (req, res) {
  res.send("boop =^..^=");
})

app.listen(3000)
```

**Comment by gosoccerboy5** [comment]
> I’m considering an alternative, that being an application project. Via this method people who can’t access GitHub will be still able to apply, without parental controls issues.

That's an interesting idea, considering it would be easier to control an application list

**Comment by BarelySmooth** [comment]
> > > I’m considering an alternative, that being an application project. Via this method people who can’t access GitHub will be still able to apply, without parental controls issues.
> > 
> > 
> > Bro, that's the best idea ever. Maybe i could combine it with my alternative and people can submit thier applications using cloud instead of a comment.
> 
> That would be nice, but what would the others think?

But if we use cloud variables, it would be disallowed for the same reasons cloud chat projects are not allowed.  (sorry if I misinterpreted what you meant)

**Comment by CodeGuy92** [comment]
> > > > I’m considering an alternative, that being an application project. Via this method people who can’t access GitHub will be still able to apply, without parental controls issues.
> > > 
> > > 
> > > Bro, that's the best idea ever. Maybe i could combine it with my alternative and people can submit thier applications using cloud instead of a comment.
> > 
> > 
> > That would be nice, but what would the others think?
> 
> But if we use cloud variables, it would be disallowed for the same reasons cloud chat projects are not allowed. (sorry if I misinterpreted what you meant)

So, we back to commenting then?

**Comment by Scratchykit-Iz-Github** [comment]
> > > > I’m considering an alternative, that being an application project. Via this method people who can’t access GitHub will be still able to apply, without parental controls issues.
> > > 
> > > 
> > > Bro, that's the best idea ever. Maybe i could combine it with my alternative and people can submit thier applications using cloud instead of a comment.
> > 
> > 
> > That would be nice, but what would the others think?
> 
> But if we use cloud variables, it would be disallowed for the same reasons cloud chat projects are not allowed. (sorry if I misinterpreted what you meant)

Project Comment threads could also work.

**Comment by CodeGuy92** [comment]
https://scratch.mit.edu/studios/30058522/comments
For anyone that ones to be invited to this studio, please tell me.

**Comment by Scratchykit-Iz-Github** [comment]
> https://scratch.mit.edu/studios/30058522/comments
> For anyone that ones to be invited to this studio, please tell me.

I could, but I’m not a manager… I’m just a curator.

**Comment by CodeGuy92** [comment]
> > https://scratch.mit.edu/studios/30058522/comments
> > For anyone that ones to be invited to this studio, please tell me.
> 
> I could, but I’m not a manager… I’m just a curator.

Sad :(

**Comment by Scratchykit-Iz-Github** [comment]
> > > https://scratch.mit.edu/studios/30058522/comments
> > > For anyone that ones to be invited to this studio, please tell me.
> > 
> > 
> > I could, but I’m not a manager… I’m just a curator.
> 
> Sad :(

Not really something to be sad about…

**Comment by CodeGuy92** [comment]
https://scratch.mit.edu/users/LankyBox01/#comments-149660413
This message was sent automatically, meaning the code works. yay!

**Comment by CodeGuy92** [comment]
https://scratch.mit.edu/studios/30058522/comments
These were sent automatically too, lol

**Comment by CodeGuy92** [comment]
https://scratch.mit.edu/studios/30058586/comments
Eeeee

**Comment by CodeGuy92** [comment]
![1](https://user-images.githubusercontent.com/79767244/124791856-1efc5680-df55-11eb-895b-c23a575086b9.PNG)
![2](https://user-images.githubusercontent.com/79767244/124791862-1f94ed00-df55-11eb-9e2c-31391339d772.PNG)

The comment queue works, yay :D

**Comment by CodeGuy92** [comment]
@Accio1 I've made so much progress. Could you please assign me?

**Comment by Accio1** [comment]
@CodeGuy92 using a bot account to perform social actions (eg. commenting) is not allowed on Scratch. I would suggest you disable the bot before it gets banned and you get alerted.

**Comment by CodeGuy92** [comment]
> @CodeGuy92 using a bot account to perform social actions (eg. commenting) is not allowed on Scratch. I would suggest you disable the bot before it gets banned and you get alerted.

[offtopic]The last time i've spoken to a scratch team member i agreed with them that instead of alerting me, i get an instant ban.[/offtopic]

I did. Maybe instead, we can make a page where all of the applications show up, and managers can zap them like the report queue?

**Comment by Shluffy** [comment]
Maybe do something manual. We will have a user (eg post-tfh-apps-here) and people apply on that profile. The moderator will then manually add it to the site, and managers will check the website and post a response on a different profile (eg tfh-grading) and then that person will manually update the site to see the grading.

**Comment by leahcimto** [comment]
Maybe just have the managers (assuming studio manager = admin) invite them manually and comment on their profile manually. The page you made could just be to track applications.

**Comment by Shluffy** [comment]
we can also enable auto merge for these pr's and have a labeler that will label it if the files are changed

**Comment by Shluffy** [comment]
> Maybe just have the managers (assuming studio manager = admin) invite them manually and comment on their profile manually. The page you made could just be to track applications.

sounds good

**Comment by BarelySmooth** [comment]
I don't understand why this is needed. Can't we just follow the current system where someone applies on the main studio, a curator/manager posts it in Special Actions and we discuss there until we hit the reply limit (in which case we'll have to make a new thread).

This issue is for a new application page. Maybe something like theforumhelpers.github.io/apply which contains information from the old description?

**Comment by Accio1** [comment]
> This issue is for a new application page. Maybe something like theforumhelpers.github.io/apply which contains information from the old description?
@BarelySmooth that is exactly why I opened this issue. I agree that the application system doesn't really have to change that much, and all the website is really needed for at this point is to display application information. I will get to work on this today.
