### ISSUE TITLE
Feature Request: Custom bio

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#265]
**Is your feature request related to a problem?**
Yea, kinda. We should have our own dashboard or settings to modify our bio without having to do a PR.
You can use my filter to protect against profanity btw.
https://github.com/CodeGuy92/anti-profanity

**Describe alternatives you've considered**
No alternatives.

**Additional context**
You could also add the switch theme button if you add a settings page lol

**Comment by gosoccerboy5** [comment]
> You can use my filter to protect against profanity btw.

That codebase looks a little messy so we might wait a little for it to mature

**Comment by Shluffy** [comment]
Your Anti-profanity filter seems very sensitive. I don't think filtering something like "booty" is really needed. I think a less sensitive filter is needed for this. Also, if someone uses something that should not be used or is considered offensive, racist, sexist, etc then they can be "banned". This could be done by making a new filter

**Comment by leahcimto** [comment]
Would there be a way to do this without a server?

**Comment by CodeGuy92** [comment]
> Your Anti-profanity filter seems very sensitive. I don't think filtering something like "booty" is really needed. I think a less sensitive filter is needed for this. Also, if someone uses something that should not be used or is considered offensive, racist, sexist, etc then they can be "banned". This could be done by making a new filter

I can add a function to filter only custom words if you want.

**Comment by CodeGuy92** [comment]
> Would there be a way to do this without a server? Also, not sure if this would be possible but maybe people change their bio on the site and something automatically makes a pr that needs to be approved so a profanity filter wouldn't be needed.

That's actually genius!
Also, for the server part, i can just make a custom node,js server on repl.it and then we could insert a form in the forum helpers website to make a post request there.
