### ISSUE TITLE
Forum Helpers List:

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#268]
**Describe the changes needed**
new users that commented on tfh-bios need to be added

**Additional context**

**Comment by BarelySmooth** [comment]
@leahcimto can I be renamed to BarelySmooth since that is my username on Scratch?

**Comment by leahcimto** [comment]
@Accio1 ^

**Comment by Accio1** [comment]
@leahcimto @BarelySmooth 
Since the username was changed on Scratch, it would be okay to change on the site as well. Please make sure to also update the user ID.

**Comment by BarelySmooth** [comment]
> Please make sure to also update the user ID.

The user id had no change

**Comment by FunctionalMetatable** [comment]
and also could somebody change my bio to `<marquee>wheee</small>`

**Comment by leahcimto** [comment]
ok sorry i've been lazy to do this working on it now

**Comment by BarelySmooth** [comment]
This is only for the new bios and not something for a Past managers section, right?

**Comment by Accio1** [comment]
> This is only for the new bios and not for a Past managers section, right?

Yes

**Comment by Accio1** [comment]
Resolved in #281
