### ISSUE TITLE
Feature Request: Bruh add an option to not collect data

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#272]
**Is your feature request related to a problem?**
Yes. Could you add an option for users to not get their data collected? I can make a PR if you assign me.

**Describe alternatives you've considered**
Why?

**Additional context**
No thanks.

**Comment by Steve0Greatness** [comment]
Are you suggesting to stop using google analytics?

**Comment by CodeGuy92** [comment]
...no
I am suggesting to add an option to the user where they can decide if their data is collected or not

**Comment by Steve0Greatness** [comment]
@CodeGuy92, what data are you saying is collected? IPs? Locations? Browsing history?

**Comment by BarelySmooth** [comment]
> IPs?

I believe they are collected, but not shown



> Locations?

Yes, it is collected and shown.



> Browsing history?

There is no way a normal website could collect that.

**Comment by Steve0Greatness** [comment]
> > IPs?
> 
> I believe they are collected, but not shown
> 
> > Locations?
> 
> Yes, it is collected and shown.
> 
> > Browsing history?
> 
> There is no way a normal website could collect that

All I'm asking of them is what data they think is being collected.

**Comment by Steve0Greatness** [comment]
Not sure if it's possible to just stop using google analytics on some users.

**Comment by BarelySmooth** [comment]
> Not sure if it's possible to just stop using google analytics on some users.

I think, yes. But like the website's privacy policy says, users wishing to opt out can just install [this extension](https://support.google.com/analytics/answer/181881), right?

**Comment by Steve0Greatness** [comment]
> > Not sure if it's possible to just stop using google analytics on some users.
> 
> I think, yes. But like the website's privacy policy says, users wishing to opt out can just install [this extension](https://support.google.com/analytics/answer/181881), right?

yeah.

**Comment by Accio1** [comment]
> > Not sure if it's possible to just stop using google analytics on some users.
> 
> 
> 
> I think, yes. But like the website's privacy policy says, users wishing to opt out can just install [this extension](https://support.google.com/analytics/answer/181881), right?

They can also just block cookies for the site, which should stop the majority of data from being collected since Google Analytics uses cookies to track site visits.

**Comment by Quantum-Codes** [comment]
U know which city im in?!

**Comment by BarelySmooth** [comment]
> U know which city im in?!

I think no, because your location information is **not** linked to **you**. Read [this](https://scratch.mit.edu/studios/3688309/comments/#comments-156478825).

**Comment by Quantum-Codes** [comment]
> > U know which city im in?!
> 
> I think no, because the information is **not** linked to **you**. Read [this](https://scratch.mit.edu/studios/3688309/comments/#comments-156478825).

That was a great comment!

**Comment by Quantum-Codes** [comment]
Using incognito will block most tracking?

**Comment by BarelySmooth** [comment]
> Using incognito will block most tracking?

No, I think it depends on the browser you are using.

**Comment by Quantum-Codes** [comment]
Incognito blocks cookies right

**Comment by BarelySmooth** [comment]
> Incognito blocks cookies right

Yes, but that is a whole different topic (which I don't know much about)

**Comment by Steve0Greatness** [comment]
> Incognito blocks cookies right

kinda, it deletes all data from the incognito window, including cookies, local storage, and cashe, and browsing history. However, it will still run google analytics.

**Comment by CodeGuy92** [comment]
> Incognito blocks cookies right

No. Google analytics will still collect data. It's just that everything from _your_ side will be deleted, not the google analytics'

**Comment by FunctionalMetatable** [comment]
also im wondering why tfh site is advertising browser extensions

**Comment by Accio1** [comment]
> also im wondering why tfh site is advertising browser extensions

Good point. I just removed that in a commit to master.

**Comment by CodeGuy92** [comment]
I guess this is fixed with the new commit then. A button would be easier, but... eeehhhh

**Comment by Shluffy** [comment]
@Accio1 I think this is fine and allowed. see griffpatch.co.uk

**Comment by Accio1** [comment]
> @Accio1 I think this is fine and allowed. see griffpatch.co.uk

Do they share that site on Scratch?

**Comment by Steve0Greatness** [comment]
@Accio1, no, it doesn't seem like they did.

**Comment by Accio1** [comment]
> @Accio1, no, it doesn't seem like they did.

Our site is shared on Scratch so it is important that it follows the rules.
