### ISSUE TITLE
Feature Request: So...

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#273]
**Is your feature request related to a problem?**
No. I was experimenting with node.js a little, and...
https://www.theforumhelpers.tk/

I somehow implemented a sign-up button to the site. It has some flaws (like, you can leave the boxes blank and they will remain like that) but i can fix them if you think that this is a good idea.

The account system actually works, and the API data is stored as JSON
![Capture](https://user-images.githubusercontent.com/79767244/125990089-fe5168b9-c234-4177-ae81-08ff4489877d.PNG)
I didn't quite implement an encryption system yet. Because, this is currently just a demo. But, i will, if you decide to add this idea.

**Describe alternatives you've considered**
E

**Additional context**
![image](https://user-images.githubusercontent.com/79767244/125990261-bc99fb3a-ceae-4507-ac0b-cf08e0e9ad95.png)
![image](https://user-images.githubusercontent.com/79767244/125990305-b76cf5a7-086e-4ee3-a1d7-dc0fa1773d50.png)
![image](https://user-images.githubusercontent.com/79767244/125990375-e7bab8d6-4f0a-4eef-8b28-1a2a0d67b556.png)

**Comment by Accio1** [comment]
We are not allowed to collect email addresses in websites shared on Scratch (although the Scratch Wiki does, which I think is an exception). I am working on something similar using PHP, and it should be ready soon. In the future, please open show and tell topics like this in the discussions tab instead of the issues tab, as it doesn't seem like you are suggesting a specific feature here.

**Comment by Shluffy** [comment]
we could do scratch account and use something like fluffyscratch

**Comment by gosoccerboy5** [comment]
seems like overkills to me

**Comment by CodeGuy92** [comment]
> We are not allowed to collect email addresses in websites shared on Scratch (although the Scratch Wiki does, which I think is an exception). I am working on something similar using PHP, and it should be ready soon. In the future, please open show and tell topics like this in the discussions tab instead of the issues tab, as it doesn't seem like you are suggesting a specific feature here.

I am. I am suggesting to add an account feature, but ok. We can stop collecting this extra info if you want. Also nodejs is a lot better

**Comment by Accio1** [comment]
> Also nodejs is a lot better

I'm pretty sure that is a subjective opinion. Is there any official source that actually states that NodeJS is better?

**Comment by CodeGuy92** [comment]
> > Also nodejs is a lot better
> 
> I'm pretty sure that is a subjective opinion. Is there any official source that actually states that NodeJS is better?

NodeJS only has npm, so you do not need to work out how the tools work and how to install one simple fricking module.
PHP blocks the process until it's entirely calculated, meaning slower load time.
NodeJS is built on javascript, meaning it's more familiar to the contributors of this project. (The project is 28.4% javascript)
If you have big codes with PHP, it will be harder to manage.
NodeJS is more flexible and easy to learn, **javascript syntax**.

**Comment by gosoccerboy5** [comment]
<sub>did you just like your own comment</sub>

**Comment by CodeGuy92** [comment]
> did you just like your own comment

yes, and i did it again
