### ISSUE TITLE
Bug: The footer isn't at the bottom of the page on the home screen

### ISSUE THREAD

**Issue by Steve0Greatness** [theforumhelpers/theforumhelpers.github.io#276]
**Describe the bug**
Not 100% sure if it is a bug, but on the homepage, for some reason on (my device at least)
![Screenshot 2021-07-17 5 57 42 PM](https://user-images.githubusercontent.com/75220768/126276929-c608dbc8-d056-43dd-a752-7cf629d0bb9e.png)
###### note: this is with the apply alert closed 

**To Reproduce**
Head to the homepage, open dev tools, switch device toolbar on, and then set the device to an iPad pro(you may not need to switch it)

**Expected behavior**
What I think is meant to happen is that it's meant to be on the bottom of the screen

**Browser Information**
I use Chrome OS, with screen dimensions of 1920x1080, it seems to work on other browsers, I haven't tested it out with other OSes yet, however

**Additional context**
no other context I can think of as of currently.

**Comment by gosoccerboy5** [comment]
Either we make a way for it to stick to the bottom, or we stretch it so it at least reaches the bottom

**Comment by Steve0Greatness** [comment]
@gosoccerboy5, I think I came up with a way to do that on #266.

**Comment by gosoccerboy5** [comment]
oh, ok. However, I tried that out earlier, and it works for your problem, but it backfires by blocking a bunch of the content.
video:
<video src="https://user-images.githubusercontent.com/82768218/126347757-256b1711-99f3-41ba-9c82-89deaccd522b.mov">


The bouncing on the screen is me trying to scroll, but I can't, and the footer now blocks the rest of the content from being viewed

**Comment by CodeGuy92** [comment]
The best solution for the footer problem is:
`position: fixed;
bottom: 0;
`

I tested it locally and it works.






Why is there `height: 110px;` when there's `height: auto`?

**Comment by Steve0Greatness** [comment]
> The best solution for the footer problem is:
> `position: fixed; bottom: 0; `
> 
> I tested it locally and it works.
> 
> Also why is there `height: 110px;` when there's `height: auto`?

it still has the same issued

**Comment by CodeGuy92** [comment]
> > The best solution for the footer problem is:
> > `position: fixed; bottom: 0; `
> > I tested it locally and it works.
> > Also why is there `height: 110px;` when there's `height: auto`?
> 
> it still has the same issue as [#276 (comment)](https://github.com/theforumhelpers/theforumhelpers.github.io/issues/276#issuecomment-883468885)

Maybe for some devices only

**Comment by Steve0Greatness** [comment]
@CodeGuy92, wait, are you saying that every single device that may or may not be affected by this should be checked in the code? Or do you know a better way?

**Comment by CodeGuy92** [comment]
> @CodeGuy92, wait, are you saying that every single device that may or may not be affected by this should be checked in the code? Or do you know a better way?

![image](https://user-images.githubusercontent.com/79767244/127672394-df5caa94-5d70-42bc-92cd-b696a9e6e258.png)

**Comment by Steve0Greatness** [comment]
> > @CodeGuy92, wait, are you saying that every single device that may or may not be affected by this should be checked in the code? Or do you know a better way?
> 
> ![image](https://user-images.githubusercontent.com/79767244/127672394-df5caa94-5d70-42bc-92cd-b696a9e6e258.png)

in no way does that answer my question.

**Comment by gosoccerboy5** [comment]
Open the developer tools and click the button that looks like that.

**Comment by CST1229** [comment]
Or you can just zoom out.

**Comment by Accio1** [comment]
If no one else has a better solution, adding `min-height: calc(100vh - 305px);` to .homeContent will fix this. However, it will have to be updated if the height of the footer or header changes.

Would anyone like to be assigned?

**Comment by CST1229** [comment]
Maybe that solution but using a CSS variable for the footer height so you don't have to change it in 2 places?

**Comment by Steve0Greatness** [comment]
@Accio1, yep, that seems to fix it.

**Comment by Accio1** [comment]
@Steve0Greatness would you like to submit a PR?

**Comment by Steve0Greatness** [comment]
@Accio1, sure. Can you assign me?

**Comment by Accio1** [comment]
Resolved by #292
