### ISSUE TITLE
Feature Request: Add this project in the application info page

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#278]
**Is your feature request related to a problem?**
No. I just think it would be a good idea to add this project in the application info page.
https://scratch.mit.edu/projects/556797590/

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Shluffy** [comment]
why poop?

**Comment by gosoccerboy5** [comment]
In my opinion the project doesn't feel very formal. Also, are you sure you can consistently keep up with the codeword? I feel like an application page is good for now, or maybe a different project..

**Comment by Quantum-Codes** [comment]
Idont know the point... the website explains better.... and if you embed a light mode project in dark mode website(I have dark mode) then it looks horrible... if I was some animation showing stuff/ an application generator, then I think it would be better

**I AM NOT A PART OF TFH..  I am speaking my opinion**

**Comment by CodeGuy92** [comment]
nvm
