### ISSUE TITLE
No need to make a different folder for each page

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#279]
If you have github pages turned on, you can actually just delete the folders and move every page to the root folder, and you can still access it without the .html at the end. Github won't redirect it :)

**Comment by Accio1** [comment]
How would this impact local development?

**Comment by CodeGuy92** [comment]
> How would this impact local development?

Haven't thought of it, tough...

**Comment by gosoccerboy5** [comment]
Making a folder for pages means:
 - the link works even with a `/` at the end of the url
 - you can add [extra files in the same folder](https://github.com/theforumhelpers/theforumhelpers.github.io/tree/master/forumhelpers) without cluttering the root folder
