### ISSUE TITLE
Feature Request: Merge QuickReply Style Sheet into this.

### ISSUE THREAD

**Issue by Steve0Greatness** [theforumhelpers/theforumhelpers.github.io#286]
**Is your feature request related to a problem?**
Sorta. It will just make developing _themes for QuickReply_(see 38, in the QuickReply repo, or go to https://quickreply.stevesgreatness.repl.co) easier.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No addition context should really be needed.

**Comment by Accio1** [comment]
QuickReply is being discontinued, see #325
