### ISSUE TITLE
Documentation: Forum Helpers List Megathread

### ISSUE THREAD

**Issue by Shluffy** [theforumhelpers/theforumhelpers.github.io#288]
**What does this affect?**
issues

**Changes/Additions**
a pinned tfh list megathread

**Comment by Accio1** [comment]
What?

**Comment by Shluffy** [comment]
> > What? Please provide more detail.
> 
> I think they mean one large issue that continuously takes in new tfh requests?

exactky

**Comment by Accio1** [comment]
Individual issues keep things more organised because then a PR to update the Forum Helpers list can resolve the entire issue, and it is easy to see what changes have been made and which ones haven't.
