### ISSUE TITLE
Make CONTRIBUTING.md more visible

### ISSUE THREAD

**Issue by gosoccerboy5** [theforumhelpers/theforumhelpers.github.io#290]
I didn't even know we had the file on the repo until just now. We should at least mention it in the README or issue templates to get the most out of it, or else it's not that helpful to us if we want certain standards.

**Comment by Accio1** [comment]
This is a good idea. As you mentioned, we can't expect people to read the file if they don't know it exists. I think adding it to the README is a good idea, and potentially also the PR Template?
