### ISSUE TITLE
Better styling.

### ISSUE THREAD

**Issue by Secret-chest** [theforumhelpers/theforumhelpers.github.io#298]
I would like to make the website look better. Some ideas:
* Change all fonts to Roboto or something
* Add a shadow to the navigation menu and make it fixed
* Remove the various themes (light, dark, scratch, terminal) and replace them with only light and dark
* Cleaner background (use white instead of light blue)
* Make links some cyan color, #0000ff looks awful
* Vectorize the logo

**Comment by Secret-chest** [comment]
@Accio1 Could you please assign me?

**Comment by Steve0Greatness** [comment]
I'm not a fan.

1. Arial is fine, as they say, "if it ain't broke, don't fix it"
2. I'm not a mobile user, so I really can't comment on this.
3. Why? They look awesome!
4. That's... awful... why do people think white looks "cleaner"
5. Blue isn't that bad, and doing both that and the white background makes the links blend into the background when hovered over in light mode.
6. But it'll look exactly the same... +It needs to be redone anyway, so it would be a waste of time.

**Comment by Secret-chest** [comment]
> 1. Arial is fine, as they say, "if it ain't broke, don't fix it"
Arial is not available on Linux and looks unprofessional.
> 2. I'm not a mobile user, so I really can't comment on this.
I promise it'll be better like this.
> 3. Why? They look awesome!
Ok, fine, but I don't understand why should we have such themes.
> 4. That's... awful... why do people think white looks "cleaner"
Because it is cleaner. The text color will be #212121 so it dosen't have too much contrast.
> 5. Blue isn't that bad, and doing both that and the white background makes the links blend into the background when hovered over in light mode.
#0000ff looks outdated
The hover color can be something different from a lighter version of the color.
> 6. But it'll look exactly the same... +It needs to be redone anyway, so it would be a waste of time.
Oh ok.

**Comment by Dhuls-Scratch** [comment]
1. We can just upload a ttf file or something for Arial. the [CSS font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) exists for this purpose.
2. No opinion
3. Why should we remove them? For the sake of removing them? Some people might like the themes
4. Light blue matches the studios
5. No, it doesn't
6. The logo needs to be updated entirely, so this is pointless

**Comment by Secret-chest** [comment]
> We can just upload a ttf file or something for Arial. the CSS font-face exists for this purpose.

Arial looks awful still. It's unproffesional

**Comment by Dhuls-Scratch** [comment]
I'm a Windows user, so i copies of a few fonts
[Untitled document (1).pdf](https://github.com/theforumhelpers/theforumhelpers.github.io/files/7376710/Untitled.document.1.pdf)
A few sans-serif fonts. Which one should we use, since Arial is too unprofessional.

**Comment by Secret-chest** [comment]
> I'm a Windows user, so i copies of a few fonts
> [Untitled document (1).pdf](https://github.com/theforumhelpers/theforumhelpers.github.io/files/7376710/Untitled.document.1.pdf)
> A few sans-serif fonts. Which one should we use, since Arial is too unprofessional.
> 

They are copyrighted still. We should use Roboto, Lato, Source Sans Pro or something open source.

**Comment by Accio1** [comment]
I think it is pretty agreed upon that this might be unnecessary, especially since we are planning to redo the site's colours in #310.

@Secret-chest If you want to come up with mockups or sample code for your ideas, feel free as that might give people a better understanding of why these style changes are being requested. In the meantime though, I'm going to close this issue as it has gone stale. If you would like it re-opened, please just ask.
