### ISSUE TITLE
Bug: Codeword and application status doesn't load right away

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#299]
**Describe the bug**
On the application instructions page, the codeword and application status doesn't load right away. This is because TFH Dashboard is hosted on Heroku and it goes to sleep if it hasn't been accessed recently. This means that the page can't display the codeword and application status until TFH Dashboard wakes up and the main site is able to receive a response from the API. This could prevent people from knowing the codeword if it doesn't load by the time they finish reading the page.

**To Reproduce**
Clear your cache and visit the applications page at a time when it hasn't been accessed recently. Observe that the codeword and application status doesn't load.

**Expected behavior**
Some kind of loading screen or bar should be added to indicate that the codeword and application status is still loading, and potentially prevent people from viewing the application instructions until the page can fully load.

**Browser Information**
N/A

**Additional context**
If someone wants to take a crack at implementing this, please write the solution you are thinking of as a reply before submitting a PR.

**Comment by gosoccerboy5** [comment]
I hate to be pushy and off-topic, but any plans for open sourcing or at least posting the source of TFH Dashboard?

**Comment by gosoccerboy5** [comment]
Oh. Sorry to bother you.

**Comment by leahcimto** [comment]
In the meantime, it might be helpful to add something along the lines of "Loading, please wait" to the places that are blank while loading.

**Comment by leahcimto** [comment]
I think the dashboard might be down right now

**Comment by Accio1** [comment]
> I think the dashboard might be down right now

It's up for me. What is making you think that it is down?

**Comment by leahcimto** [comment]
> > I think the dashboard might be down right now
> 
> It's up for me. What is making you think that it is down?

It was a blank page that was taking a long time to load and the codeword on the website wasn't showing.

**Comment by Accio1** [comment]
> > > I think the dashboard might be down right now
> > 
> > 
> > It's up for me. What is making you think that it is down?
> 
> It was a blank page that was taking a long time to load and the codeword on the website wasn't showing. It's working now though.

It might have been an issue with Heroku.

**Comment by leahcimto** [comment]
A way to fix this might be having a pinger ping the site on a schedule. I know this works with replit.

**Comment by Chiroyce1** [comment]
> A way to fix this might be having a pinger ping the site on a schedule. I know this works with replit.

Yeah, I can implement one with very little downtime. I've been testing out always on repls with a non-paid account and it works really well (with only few minutes of downtime in 24-30 hours)... so an HTTP get request would be good as a ping to the server, right?

**Comment by leahcimto** [comment]
> > A way to fix this might be having a pinger ping the site on a schedule. I know this works with replit.
> 
> Yeah, I can implement one with very little downtime. I've been testing out always on repls with a non-paid account and it works really well (with only few minutes of downtime in 24-30 hours)... so an HTTP get request would be good as a ping to the server, right?

Yes, I'm pretty sure that would keep the site up. To keep my repls up, instead of having my repl ping itself, I use https://uptimerobot.com/. It works really well.

**Comment by Chiroyce1** [comment]
@leahcimto should I implement it or are you going to be doing it?

**Comment by leahcimto** [comment]
@Chiroyce1 It depends if we are implementing an external pinger or having the dashboard ping itself. If we go forward with the latter, this could be implemented in the next dashboard update. Or we could go ahead with an external pinger.
@Accio1, thoughts?

**Comment by Mbrick2** [comment]
Maybe just lag the whole thing till it comes.

**Comment by gosoccerboy5** [comment]
> Maybe just lag the whole thing till it comes.

That sounds like a pretty bad UX.

Perhaps, have a placeholder saying `{Loading...}` for the codeword until you can get it to load. Not pretty, but it would work.
However, this problem doesn't seem too bad, as I can't instantly locate the codeword and application status anyway, so I doubt users will notice this little 'error'.

**Comment by leahcimto** [comment]
If we made a pinger, it could be as simple as a GitHub action running every 10 minutes. https://github.com/leahcimto/randomJokeAPI/blob/main/.github/workflows/ping.yml

Loading placeholder text could be a temporary fix I guess.

**Comment by CST1229** [comment]
> If we made a pinger, it could be as simple as a GitHub action running every 10 minutes. [https://github.com/leahcimto/randomJokeAPI/blob/main/.github/workflows/ping.yml](https://github.com/leahcimto/randomJokeAPI/blob/main/.github/workflows/ping.yml?rgh-link-date=2022-04-24T00%3A05%3A01Z)

Or using uptimerobot or another pinger.

**Comment by leahcimto** [comment]
e2f3028 adds loading messages to where it is blank, thoughts?

**Comment by Chiroyce1** [comment]
> [e2f3028](https://github.com/theforumhelpers/theforumhelpers.github.io/commit/e2f30289c5366d21e0ab1dda872c2149b5ab9db0) adds loading messages to where it is blank, thoughts?

I'd say hide the entire sentence until the codeword loads, this way people won't think `[Loading, please wait...]` is the codeword. You could change the `display` CSS property to hide the sentence at first, and then after it loads, show it.

**Comment by leahcimto** [comment]
> > [e2f3028](https://github.com/theforumhelpers/theforumhelpers.github.io/commit/e2f30289c5366d21e0ab1dda872c2149b5ab9db0) adds loading messages to where it is blank, thoughts?
> 
> I'd say hide the entire sentence until the codeword loads, this way people won't think `[Loading, please wait...]` is the codeword. You could change the `display` CSS property to hide the sentence at first, and then after it loads, show it.

Hiding the whole sentence could make it so someone reads the whole thing and then misses the codeword because it didn't load in time, or the dashboard is blocked on their device making it never come up.

**Comment by leahcimto** [comment]
This is more urgent now as the entire list of forum helpers depends on the dashboard now. @Accio1 do you have any suggestions? I think a pinger (either GitHub Actions or dashboard pinging itself) running with placeholder text so when the dashboard is down there isn't just nothing would be a good idea. Anyone else have thoughts?

**Comment by penguinmoose** [comment]
@leahcimto Agree. A placeholder would be good. Also, can someone add or remove some tag to let people know that this might need some attention? Right now there’s a stale tag.

**Comment by penguinmoose** [comment]
@Accio1 If it’s priority high, why aren’t we fixing it?

**Comment by Accio1** [comment]
> @Accio1 If it’s priority high, why aren’t we fixing it?
> 
> I do agree that it’s pretty urgent.

Because I need to think of the best way to do this without spamming my own servers, since I am using a free tier of the service that hosts the dashboard so there are certain limits in place about the number of hours that it is allowed to run. If it is kept "awake" by a pinger constantly then these limits could be reached and then it wouldn't work for the rest of the month. 

I agree that placeholder loading text is a good temporary fix for now though.

**Comment by leahcimto** [comment]
Would it be okay if I made a PR with placeholder text?

**Comment by Accio1** [comment]
> Would it be okay if I made a PR with placeholder text?

Yes, that would be great thanks!

**Comment by Accio1** [comment]
I believe that the placeholder loading text is the best option that we have at the moment, because after doing more research, a pinger would definitely cause problems with the dashboard and therefore should not be used. If anyone has an idea that is different than just placeholder text but does not involve a pinger, feel free to suggest it.
