### ISSUE TITLE
[Bug] Issues with list of Forum Helpers

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#30]
Upon inspecting the list of Forum Helpers after #28 was merged, I noticed the following issues when the list of Forum Helpers was compared to the list of curators/managers in the studio. 

- LegoManiac04 should come before Geonaut in the list of Forum Helpers
- awesome_guy_360 is missing (between jakel181 and orochi67). Looking through commit logs, it looks like they were simply missed in the original commit to add this list, and it hasn't been noticed since.
- nickeljorn is missing (between AfraidRacer and rainpelt28). Looking through commit logs, it looks like they weren't transferred when the site switched from biographies being coded directly to using JSON.
- bidulule is missing (between LuckyLucky7 and 54329). Looking through commit logs, it looks like they weren't transferred when the site switched from biographies being coded directly to using JSON.

**Comment by Accio1** [comment]
Triage Information

Priority: High (This displays incorrect information about who is a part of the Forum Helpers, and therefore should be fixed ASAP. However, it isn't a site-breaking bug, and therefore doesn't warrant the "URGENT" label.)
Timeline for fix: Within the next week

**Comment by leahcimto** [comment]
I could help if you would like me to.

**Comment by leahcimto** [comment]
I could help if help is wanted.

**Comment by Accio1** [comment]
@leahcimto please go ahead and work on this!

**Comment by leahcimto** [comment]
> @leahcimto please go ahead and work on this!

Awesome, I'll get started tomorrow.

**Comment by Accio1** [comment]
> > @leahcimto please go ahead and work on this!
> 
> Awesome, I'll get started tomorrow.

Fantastic! I've assigned you to this issue

**Comment by leahcimto** [comment]
@Accio1 I can't seem to find awesome_guy_360 in the studio. The Scratch account does not curate the studio. Was that a mistake?

**Comment by leahcimto** [comment]
Anyways, I made the PR. Let me know if anything should be changed.
