### ISSUE TITLE
Forum Helpers List: Bios need updating

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#300]
**Describe the changes needed**
Users that have requested on the TFH-Bios Scratch account need bio updates, and new forum helpers need to be added.

**Additional context**
I am marking this as good first issue. If anyone wants to implement this, feel free to ask.

**Comment by leahcimto** [comment]
I'm going to implement this now.

**Comment by leahcimto** [comment]
Nevermind, as stated in #280, the bio list should be frozen, and a new one needs to be created with the new studio.

**Comment by penguinmoose** [comment]
I think adding new forum helpers is pretty important right now. Not everyone can access the dashboard right now.

**Comment by leahcimto** [comment]
> I think adding new forum helpers is pretty important right now. Not everyone can access the dashboard right now.

See #303, I've been updating the list and it will be pushed soon.
