### ISSUE TITLE
Move all members currently on the List of Forum Helpers page to another page (Past Members).

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#302]
The forum helpers list page needs to be moved to another json file and a new files need to be created.

I will implement this ASAP.

Two new files will be created, pastmanagers.json and pastcurators.json and will be displayed on another page (this issue is just for making the files, not the new page)

The managers.json and curators.json files will have a `original: false` or `original: true` which states if they are in the original studio.

Note that this includes adding new users.

EDIT: Pull request up! #303

**Comment by leahcimto** [comment]
Because of this new users can't be added, so it needs to be implemented ASAP.

Users that were in the original forum helpers will have the same bios unless a new one was requested.

**Comment by Accio1** [comment]
@leahcimto feel free to work on this. It will also make populating the dashboard with current members a lot easier.

**Comment by leahcimto** [comment]
Sorry this is taking so long, I hope to have it done soon.

**Comment by leahcimto** [comment]
I've finished the new managers file.

**Comment by leahcimto** [comment]
@Accio1 A user in the studio has an account that is deleted, but it still shows in the studio because of the new update. Should I add them to the list?

**Comment by leahcimto** [comment]
Blocked pending dashboard update.
