### ISSUE TITLE
Google Analytics link when declining analytics

### ISSUE THREAD

**Issue by webdev03** [theforumhelpers/theforumhelpers.github.io#304]
**What does this affect?**
privacy policy and notice

**Changes/Additions**
originally posted at https://scratch.mit.edu/studios/30136012/comments/#comments-171455099
Your website which alerts the user to Google Analytics, when you press "Leave Site" it takes you to scratch, which (fun fact) has Google Analytics, so instead make it `window.history.back()` or `about:blank`.

**Comment by gosoccerboy5** [comment]
Anyone interested in TFH is probably from Scratch, so this wouldn't make much of a difference.
`window.history.back()` might not work if they don't have browser history for that tab (for example, if they command+clicked a link to get here).

> i guess you're right, maybe instead so tat it actually shows that you are going to that studio instead of making a wild guess which is the current system

maybe a tooltip?

**Comment by webdev03** [comment]
Your button to return isn't an anchor tag and so you can't see that you are going to Scratch.

**Comment by webdev03** [comment]
> `window.history.back()` might not work if they don't have browser history for that tab (for example, if they command+clicked a link to get here).

```js
window.history.back()
window.location.href = "about:blank"
```
this works

**Comment by gosoccerboy5** [comment]
i think that force redirects to about:blank even if you have history for that atb

**Comment by gosoccerboy5** [comment]
```js
if (document.referrer !== "") {
  window.history.back();
} else {
  window.location.replace("about:blank");
}
```
maybe?

**Comment by Chiroyce1** [comment]
@gosoccerboy5 `document.referrer` doesn't seem to work very well. In most cases people visit the TFH site from Scratch, I tried doing that and it returns blank...

https://user-images.githubusercontent.com/97374054/148873163-d9cf1111-064e-4582-ae47-c56ec131e411.mov

**Comment by gosoccerboy5** [comment]
oh :/ i didnt read the mdn page fully 😕

**Comment by gosoccerboy5** [comment]
oh wait i just realized u have a github account now

**Comment by Chiroyce1** [comment]
`about:home` in Firefox takes you to the homepage, but you aren't allowed to use it in JavaScript

<img width="578" alt="image" src="https://user-images.githubusercontent.com/97374054/149614044-1e7158a0-6883-4368-bf1a-bfe88e9ab301.png">

is it the same for Chrome?

**Comment by webdev03** [comment]
`window.location.replace('about:blank')` is the easiest solution

**Comment by Chiroyce1** [comment]
That'll make people scared - wondering why their entire browser screen went black/white without an address in the URL bar...

**Comment by webdev03** [comment]
Or just remove the `Leave Site` button and replace it with "by continuing to use the site you agree to have your data sold by google" or something like that

**Comment by Steve0Greatness** [comment]
> 

I'd just like to clarify this to you: Google does not "sell" you data. They keep it to themselves, selling it to other ad agencies would defeat their entire way of making money.  
Also, when using Google analytics, Google gives the site's admin the ability to disable Google tracking their users. However, there's no way to prove if they are actually turning it off.

**Comment by webdev03** [comment]
I was joking! Sorry. (You can mark this as offtopic)
