### ISSUE TITLE
Forum Helpers List: Changes

### ISSUE THREAD

**Issue by derter-menter** [theforumhelpers/theforumhelpers.github.io#305]
**Describe the changes needed**
Some users need to be added to the page. This includes @rayli1123, @god286, @TheGlassPenguin, @prime689, @b1048546, @exphire, @helloworldbyeworld and @mrcreatorlugi

@chiryoce and @maximouse should be moved to the manager section

**Comment by derter-menter** [comment]
Feel free to assign this to me

**Comment by Chiroyce1** [comment]
I'll make a Python Script to make it easier, so we don't have to manually add the names to the JSON files.

**Comment by leahcimto** [comment]
Duplicate of #302
