### ISSUE TITLE
Feature Request: Opt Out of Google Analytics option

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#306]
**Is your feature request related to a problem?**
Not really, however some users have shown concerns for the use of Google Analytics on this website. This suggestion is a way to opt out of it.

**Describe alternatives you've considered**
I can't really think of any.

**Additional context**
None

**Comment by gosoccerboy5** [comment]
cookies? localstorage? how would this option be stored

**Comment by leahcimto** [comment]
> cookies? localstorage? how would this option be stored

I think localstorage would be best

**Comment by Steve0Greatness** [comment]
> > cookies? localstorage? how would this option be stored
> 
> I think localstorage would be best

Yeah, Cookies are hard to work with in browser JS.

**Comment by Shluffy** [comment]
I believe this would have to be done on their side. I believe that an admin of an organization can turn it off for everyone, so this may be possible on the visitor's side. Not sure what we could do here, other then just removing it.

**Comment by Weredime** [comment]
> I believe this would have to be done on their side. I believe that an admin of an organization can turn it off for everyone, so this may be possible on the visitor's side. Not sure what we could do here, other then just removing it.

what the heck are you talking about

**Comment by Weredime** [comment]
To be honest when you press the leave site button you are redirected to scratch.mit.edu which also has google analytics lol

**Comment by leahcimto** [comment]
> I believe this would have to be done on their side. I believe that an admin of an organization can turn it off for everyone, so this may be possible on the visitor's side. Not sure what we could do here, other then just removing it.

I don't really understand your comment, could you elaborate on what you mean?

**Comment by leahcimto** [comment]
> To be honest when you press the leave site button you are redirected to scratch.mit.edu which also has google analytics lol

#304

**Comment by Shluffy** [comment]
> I believe this would have to be done on their side. I believe that an admin of an organization can turn it off for everyone, so this may be possible on the visitor's side. Not sure what we could do here, other then just removing it.

To explain here, I believe in a google organization (like a school or buisness) the organizations admins can turn off google analytics for the entire organization. It may be possible to do without an organization, I am not sure tho. The other option if this doesn't work would be to plain remove it.

**Comment by Shluffy** [comment]
Would a vpn work to block google analytics?

**Comment by Weredime** [comment]
> Would a vpn work to block google analytics?

Nope, the script still runs.

Probably better to use an extension for blocking analytics

**Comment by leahcimto** [comment]
Closing as GA will be removed in the next update.
