### ISSUE TITLE
Bug: Typo in theme switcher button

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#308]
**Describe the bug**

<img width="292" alt="Screen Shot 2022-03-16 at 6 58 37 PM" src="https://user-images.githubusercontent.com/68165163/158704923-2b7bc383-27ac-44a9-bec8-33604dab21c4.png">
In this text, "Scratch" is not capitalized. It should be because Scratch is a proper noun in this context.

**To Reproduce**
Change theme to Scratch, then look at the theme switcher button.

**Expected behavior**
Scratch should be capitalized.

**Browser Information**
Not applicable.

**Additional context**
Note that capitalizing the string "scratch" in this array will cause the page to break. https://github.com/theforumhelpers/theforumhelpers.github.io/blob/1e5b0ba55b117bca4808e0887b89bce3a3eb2469/resources/theme.js#L28

**Comment by Steve0Greatness** [comment]
All elements in the array could be an object.  
`{ name: "scratch", display: "Scratch" }`  
But this likely isn't the best solution.

**Comment by Steve0Greatness** [comment]
Could I be assigned?

**Comment by leahcimto** [comment]
To be honest this really isn't that big of a deal and the solutions will be overly complex, so I will close this.
