### ISSUE TITLE
Feature Request: Additional Features for the "List of Forum Helpers" Page.

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#31]
The List of Forum Helpers page contains information about the people who are currently Forum Helpers, but I feel as though it is lacking some features that could be beneficial.

- [ ] It would be neat to add different filters for sorting the list. For example, sorted by date joined (default used currently), or sorted alphabetically. I'm not sure how feasible this is based of of how the JSON is organised, but I will do some research to see if this is possible without creating an entirely separate JSON list that is sorted alphabetically. 

- [x] There should be a counter that shows the number of Forum Helpers, as well as how many curators and managers there are. This shouldn't be too difficult to implement.

- [x] Not necessarily a feature, but the distinction between the curator and manager sections needs to be greater. Just scrolling, it is hard to tell where the list of managers ends and where the list of curators begins because the headings blend in with the rest of the content of the page.

- [x] Integrate shefwrld/ocular/scratchDB to display post counts and other info next to user's names.

**Comment by Accio1** [comment]
Triage Info

**Priority:** Low priority because it contains optional features that may be added in a future update.
**Timeline:** This will be worked on as a part of the site overhaul taking place near the end of this year/start of next year.

**Comment by leahcimto** [comment]
Part of this has been completed.

**Comment by Accio1** [comment]
> Part of this has been completed.

@leahcimto Edited to reflect which ones are done. I'm not sure if number one is worth the time it would take to implement. Thoughts?

**Comment by leahcimto** [comment]
@Accio1 I agree.

**Comment by Accio1** [comment]
Okay, I'm going to go ahead and close this.
