### ISSUE TITLE
Update TFH header icon, and what should it be?

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#319]
### Discussed in https://github.com/theforumhelpers/theforumhelpers.github.io/discussions/318

<div type='discussions-op-text'>

<sup>Originally posted by **penguinmoose** July 16, 2022</sup>
On the TFH website, the header icon is still from the old studio. I think it would be nice if we update the icon to something like the current (new studio) thumbnail.

Since the text in the studio thumbnail is a bit small compared to the background, I'm thinking we could make it a cropped version of the studio thumbnail (example linked at the bottom). Also, the aspect ratio of the thumbnail is rectangular, so either we only crop the sides or we can make the icon rectangular as well (though that might not look very good).

Example of square icon:

<img width="187" alt="tfh square example" src="https://user-images.githubusercontent.com/67451414/179375605-21bc9818-8939-444c-a912-4f1f41f18020.png">

What do you think?</div>

**Comment by penguinmoose** [comment]
Ok thanks for making it for me (I'm still kinda new to this stuff)

**Comment by leahcimto** [comment]
Slightly related to #310

**Comment by penguinmoose** [comment]
> Slightly related to #310

Right. I was also going to say that we should update the theme too.

**Comment by gosoccerboy5** [comment]
Set border-radius to 10px. Not bad, but the text is proportionally a little too small in the image.
![Screen Shot 2022-07-17 at 8 21 47 PM](https://user-images.githubusercontent.com/82768218/179433297-8d51ba50-1f53-4b4b-a765-945bf51bc930.png)

**Comment by gosoccerboy5** [comment]
doesn't really match the site's theme tho.

**Comment by Accio1** [comment]
I think it would be good to do a condensed version of the thumbnail similar to the one that we have now, which took the old thumbnail and focused on only a few elements of it in order to make it smaller but recognizable.

**Comment by Accio1** [comment]
For reference, these are the colours in the thumbnail:

Far Left Pea Green - #d8d934
Middle Orange - #fc9745
Right Yellow - #ffcd5d
Far Right Blue - #46a3ff
Top Speech Bubble - #7c84ba
Bottom Speech Bubble - #485189
Text - #f2f2f2

**Comment by gosoccerboy5** [comment]
If you need any JS help I might be able to chip in

**Comment by Accio1** [comment]
How about something like this?
![TFHLogo1](https://user-images.githubusercontent.com/48496940/179434899-ed9b58d8-f67a-44f0-95a5-89dcc17c31f9.png)
Or this:
![TFHLogo2](https://user-images.githubusercontent.com/48496940/179434902-32f98574-28f0-4e8f-af72-093de70eb8e9.png)

**Comment by gosoccerboy5** [comment]
![Screen Shot 2022-07-17 at 8 56 20 PM](https://user-images.githubusercontent.com/82768218/179435091-b8f21a32-68e9-4348-be6c-322d1e96661c.png)
![Screen Shot 2022-07-17 at 8 56 41 PM](https://user-images.githubusercontent.com/82768218/179435116-76bdc1a9-8db0-42da-bb08-b362222c809b.png)

**Comment by Accio1** [comment]
> ![Screen Shot 2022-07-17 at 8 56 20 PM](https://user-images.githubusercontent.com/82768218/179435091-b8f21a32-68e9-4348-be6c-322d1e96661c.png) ![Screen Shot 2022-07-17 at 8 56 41 PM](https://user-images.githubusercontent.com/82768218/179435116-76bdc1a9-8db0-42da-bb08-b362222c809b.png)

In #310 we're discussing updating the site's light theme in order to match the theme colours of the current thumbnail.

**Comment by gosoccerboy5** [comment]
cool.

**Comment by penguinmoose** [comment]
I love the second one @Accio1 listed too. We'll round the corners. I think that is the best option.

**Comment by BarelySmooth** [comment]
The header icon would also be the favicon, so it shouldn't have a lot of text on it. (FH or TFH would be fine, like the current one does).

This is how it would look (on Chrome)
<img width="617" alt="image" src="https://user-images.githubusercontent.com/83728060/179727940-49c4267a-4c74-490a-b74f-09f36fe8aff4.png">

In my opinion, the second one Accio sent would be a better choice:
<img width="612" alt="Screenshot 2022-07-19 at 2 26 11 PM" src="https://user-images.githubusercontent.com/83728060/179729154-c9bd9721-a625-422c-9e2d-4274c3ddef9f.png">

**Comment by Accio1** [comment]
> It looks like we are all in favor of the second icon Accio1 listed. @Accio1, are we ready to make a PR and push to the main site, or should we wait for theme changes?

If no one disagrees, I think we can go ahead with this.

> Edit: one thing though- the "TFH" in the second icon looks slightly off centered. I don't know if that's an illusion or something but is anyone else seeing that? Not sure if it is such a big deal because this icon will be displayed relatively small but maybe something to note.

Good catch. It wasn't centred so I fixed it and it is now.

**Comment by Accio1** [comment]
Does this rounded version look good to everyone?
![TFHLogoRound](https://user-images.githubusercontent.com/48496940/180071226-1c12129a-f3cd-4541-82ec-d8ce3f32843e.png)

**Comment by penguinmoose** [comment]
@Accio1 Looks great. I think we can go ahead.

**Comment by penguinmoose** [comment]
@Accio1 But we shouldn’t delete the old icon (we should put it somewhere). The old icon will probably show up with the “old” theme (discussed in #310), but that will come later.

**Comment by leahcimto** [comment]
I could replace the icon and make a  PR if we are good to go ahead with that.

**Comment by leahcimto** [comment]
Yeah that would be a good idea. We could move it to a file like icon_old.png

> @Accio1 But we shouldn’t delete the old icon (we should put it somewhere). The old icon will probably show up with the “old” theme (discussed in #310), but that will come later.


Yeah that would be a good idea. We could move it to a file like icon_old.png

that awkward moment when you edit someone's comment instead of quoting it 😳

**Comment by Accio1** [comment]
> I could replace the icon and make a  PR if we are good to go ahead with that.

I've already got it set up on a branch but I'm not at home right now so I can get to it tomorrow.

**Comment by penguinmoose** [comment]
@Accio1 @leahcimto Also, I think it would be good to change the GitHub organization icon to the new one.
