### ISSUE TITLE
TFH Dashboard Down for Maintenance 17/7/22

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#324]
TFH Dashboard is down for maintenance starting July 17th 2022 at 6:10 PM EST.

Reason(s):
- Adding the ability for curators to log in
- Converting the list of Forum Helpers from a JSON file to a database
    - This also includes the feature of being able to change your bio
- Adding a few new api endpoints

Impact:
- Visiting any part of the dashboard will result in a maintenance page.
- Application status and codeword is not displayed on the main site.
- At some points, the list of Forum Helpers may fail to load as it transitions to loading from a database instead of JSON files. 

Estimated return of service:
Afternoon of July 19th 2022 or earlier

Return of service will include an announcement detailing the new features and how to access them.

**Comment by penguinmoose** [comment]
Will this update also add new users so the newest managers can use the dashboard?

**Comment by leahcimto** [comment]
> Will this update also add new users so the newest managers can use the dashboard?

Yes, it will.

**Comment by MaterArc** [comment]
This seems like a pretty cool update!

**Comment by Accio1** [comment]
> @Accio1, Is it okay for me to delete branches that have already been merged to help clean things up?

Yep, that's fine.

**Comment by Accio1** [comment]
Downtime is over! See #329 for more information!
