### ISSUE TITLE
Feature Request: Make the “The Forum Helpers” text in the header also link to the hompage

### ISSUE THREAD

**Issue by penguinmoose** [theforumhelpers/theforumhelpers.github.io#333]
I feel like that when on a page on the website, it is not obvious how to go back to the hompage. Usually, the name of the website in the hompage links to the hompage when clicked. I think it would be better and more intuitive to make it so that both the text (“The Forum Helpers”) and the icon link to the hompage.

Even better, when they (the icon and the text, as a whole) are hovered on, there will be a slight rounded background to show that clicking the icon or the text will do something.

I actually didn’t know how to go back to the hompage (other than using the browser’s back button) until today.

**Comment by Accio1** [comment]
Most sites seem to have it so that if you click the general area of the title or icon it directs to the homepage, so I would like to do something similar. If they are both wrapped in a `<span>` tag which is the height of the header it should be easy to turn them all into a link.

**Comment by penguinmoose** [comment]
@Accio1 Right. Wrapping them in a `<span>` tag would be good because they don't really have many default properties (unlike `<div>`).
