### ISSUE TITLE
Feature Request: Website Contributor Icons/Emojis

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#341]
**Is your feature request related to a problem?**
No, however this has been discussed before and I think it would be a good idea to have contributor badges of some sort on the forum helpers list page. Also possibly for dashboard admins. It could be just an emoji next to their username, and I think it would be okay if it was hardcoded instead of being updated by the dashboard.

**Describe alternatives you've considered**
Not really sure

**Additional context**
None

**Comment by Accio1** [comment]
I like this idea, and think that we could expand it to maybe have a few different badges, similar to the ones on GitHub profiles, based on certain requirements.

Here are some that I have come up with so far, does anyone else have any ideas for other badges?
![SiteBadges](https://user-images.githubusercontent.com/48496940/180667780-1798af85-fe52-4c84-aed3-6055519bef73.png)

**Comment by leahcimto** [comment]
Those look really cool!

**Comment by Accio1** [comment]
> Those look really cool!

@leahcimto do you have any suggestions for others that could be displayed?

**Comment by leahcimto** [comment]
> > Those look really cool!
> 
> @leahcimto do you have any suggestions for others that could be displayed?

At the moment no, but I'll try to think of some more.

**Comment by leahcimto** [comment]
Possibly a top 25 badge for being in the top 25 of having the most posts (https://postpercent.rirurin.com/forum/0/1). I was going to suggest post count badges but that might encourage post farming.

**Comment by penguinmoose** [comment]
@leahcimto I think a top 25 badge would not be super important, but it might be nice.

@Accio1 Also, I suppose we will manually update the badges (making it auto will probably be pretty hard), right? If so, it shouldn't be too hard.

**Comment by leahcimto** [comment]
These things don't change very often (if at all) so they would likely be hardcoded.

**Comment by leahcimto** [comment]
Does anyone have any ideas on how to implement this?

**Comment by BarelySmooth** [comment]
> Does anyone have any ideas on how to implement this?

We could add entries containing badge information to the JSON files that contain manager/curator data
