### ISSUE TITLE
Bug: Codeword doesn't load

### ISSUE THREAD

**Issue by Dhuls-Scratch** [theforumhelpers/theforumhelpers.github.io#348]
**Describe the bug**
A clear and concise description of what the bug is. Please use screenshots if applicable.

The codeword (and application status) don't load

**To Reproduce**
Steps to reproduce the bug

Go to https://theforumhelpers.github.io/apply/

**Expected behavior**
A clear description of what you expected to happen.

The codeword loads

**Browser Information**
Include details about your browser and OS here. If possible, please identify if this is happening on just your browser and OS, or other ones as well.

Microsoft Edge 103 Windows 10 21H2

**Additional context**

Is dashboard supposed to be down right now? Because it is

**Comment by Accio1** [comment]
Sorry about that. Should be working now.
