### ISSUE TITLE
Use uploads.scratch.mit.edu rather than cdn2

### ISSUE THREAD

**Issue by Weredime** [theforumhelpers/theforumhelpers.github.io#349]
Scratch recently created a redirect from images at `cdn2.scratch.mit.edu` to `uploads.scratch.mit.edu`. We should save them a redirect.
https://github.com/theforumhelpers/theforumhelpers.github.io/blob/57f024c5c64ba6832cdd3e39d175ade3e7b2826f/forumhelpers/FHP.js#L19

@Accio1 Could I be assigned? I have a branch at https://github.com/Weredime/tfh-site.fork/blob/chore/update-profile-images/forumhelpers/FHP.js ready for PRing

**Comment by leahcimto** [comment]
@Weredime Since this is such a small change feel free to submit a PR. I could have sworn we changed from cnd2 to uploads a while ago (#45), but I guess it was changed back. I will assign you now.

**Comment by Accio1** [comment]
> I could have sworn we changed from cnd2 to uploads a while ago (#45), but I guess it was changed back. I will assign you now.
Strange. I remember making that change so it must have been changed back mistakenly between then and now.
