### ISSUE TITLE
Feature Request: Link to TFH GitHub in the header

### ISSUE THREAD

**Issue by Adzboy** [theforumhelpers/theforumhelpers.github.io#354]
Link to https://github.com/theforumhelpers/theforumhelpers.github.io/ in the header of the website so people can see where to contribute.

**Comment by gosoccerboy5** [comment]
I think it's in the website's footer.

**Comment by Adzboy** [comment]
> I think it's in the website's footer.

Whoops, didn't notice that. Nevermind then
