### ISSUE TITLE
Dashboard down?

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#357]
The dashboard is currently down for me. Is anyone else experencing this issue? I'm getting this:

<img width="789" alt="Screen Shot 2022-08-23 at 8 42 59 PM" src="https://user-images.githubusercontent.com/68165163/186290233-d523bcdc-aa24-4175-85cf-30b5c4db2258.png">
?

@Accio1

**Comment by Accio1** [comment]
Try it again now. It worked for me but had an unusually long loading time so maybe your computer timed out before it loaded?

**Comment by leahcimto** [comment]
Working now. I guess it could have been an issue with Heroku or my internet connection.
