### ISSUE TITLE
Idea: Update credits area

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#36]
The credits area in the footer currently says "This website was made by -Accio- (Accio1 on Github) and NilsTheBest (NilsTheBest on Github) on behalf of the Forum Helpers", however, there are some other users who have helped this website, like the people in [the forum helpers organization](https://github.com/orgs/theforumhelpers/people), and others who are not in that list.

**Comment by Accio1** [comment]
Thanks for creating an issue for this. I have mentioned it in the to do list for the site overhaul ( https://github.com/theforumhelpers/theforumhelpers.github.io/discussions/35 ) (Make sure to check out and post in the new discussion section of this repository!). I was thinking that there could be either:
a) A credits page that shows who has contributed to the site
b) Badges next to people's names on the List of Forum Helpers page which link to their GitHub profile when clicked and display a tooltip indicating that the person helped code the website when hovered over.

Which one of those would you prefer?

**Comment by leahcimto** [comment]
I think the first option would be easier, but the second option would probably look nicer. I would go for the second option, however this will most likely be harder to implement.

**Comment by Accio1** [comment]
@leahcimto I would also prefer the icons but I'm not sure how easy it will be to pull off. I will try both options and choose the one that is more realistically possible.

**Comment by MTM828** [comment]
I honestly think taht the credits should have their own page and the footer should have page links and such, like Scratch's. But yeah, I understand that it's fine just the way it is.

**Comment by Accio1** [comment]
@MTM828 @leahcimto maybe a combination of both? There could be badges indicating someone has helped with the site, and then a credits page with a more detailed description of each contributer?

**Comment by leahcimto** [comment]
> @MTM828 @leahcimto maybe a combination of both? There could be badges indicating someone has helped with the site, and then a credits page with a more detailed description of each contributor?

I like that idea 👍

**Comment by MTM828** [comment]
@Accio1 Yeah, yeah, great idea!

**Comment by leahcimto** [comment]
Just throwing this out there, we could also use something like [this](https://allcontributors.org/). I know that ScratchAddons was able to make it so the bot also puts things on their credits page, not just the readme.

**Comment by leahcimto** [comment]
Are there anymore ideas on this?

**Comment by Accio1** [comment]
I've looked into using all contributors but it seems a little bit like overkill for the small number of contributors that this project has. After fix styling issue is resolved, I will start working on this in order to prevent merge conflicts.

**Comment by leahcimto** [comment]
> I've looked into using all contributors but it seems a little bit like overkill for the small number of contributors that this project has. After fix styling issue is resolved, I will start working on this in order to prevent merge conflicts.

@Accio1 Agreed. When do you plan on working on this?

**Comment by Accio1** [comment]
@leahcimto I'm very sorry about the delay. School and another project that I am working on is taking up the majority of my time right now. Since I am busy, I think for now I will work on just a very simple static credits page with just a list of names and icons. Then, when I have more time on my hands, I will work on adding more complex features such as badges on the list of forum helpers page or commit counts on the credits page, etc.

**Comment by leahcimto** [comment]
Got it!

**Comment by Accio1** [comment]
In progress right now. I am thinking of having a grid of people similar to the Scratch Credits page with their GitHub profile and username. Does this sound good?

**Comment by leahcimto** [comment]
Sounds good to me! Also, the labeler is working :D

**Comment by Accio1** [comment]
@leahcimto how do you think it should be organised? Alphabetical? Most to least contributions? Oldest to earliest?

Also I'm glad that the labeler is working!

**Comment by leahcimto** [comment]
I think most to least contributions, but you can do alphabetical if you think that's better :)

**Comment by Accio1** [comment]
@leahcimto how does this look?
![image](https://user-images.githubusercontent.com/48496940/110224057-6a6aff00-7ea6-11eb-9770-bf1207b77b62.png)

**Comment by leahcimto** [comment]
@Accio1 That looks amazing!

**Comment by Accio1** [comment]
@leahcimto Thanks! I'm going to make the PR now!
