### ISSUE TITLE
[Bug] Byron_Inc's PFP hasn't been updated

### ISSUE THREAD

**Issue by MTM828** [theforumhelpers/theforumhelpers.github.io#40]
This isn't SOO important but yeah, Byron's PFP is old.

**Comment by MTM828** [comment]
Why does this have the "needs info" tag?

**Comment by Accio1** [comment]
It is up to date for me. This might have been a caching issue. Try clearing your cache and reloading the page.

The way that this site is designed, it is impossible for a profile picture to not be up to date. It pulls the picture right from Scratch using the person's user ID.

**Comment by MTM828** [comment]
Hmm, OK thanks. Resolved I guess.

**Comment by leahcimto** [comment]
Also, it might be an issue with your cache. Try doing ctrl+shift+R, or clear your cache (it is different depending on what browser you use)

**Comment by MTM828** [comment]
@leahcimto Yeah, it probably is, thanks. And I'm using Edge.
