### ISSUE TITLE
[Bug] cnd2 to uploads

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#42]
Currently, this site uses cnd2 to get a user's profile picture. Recently, the 'image hosting' Scratch uses, was changed from cnd2.scratch.mit.edu to uploads.scratch.mit.edu. In the list of forum helpers, it gets the user's profile picture through cnd2. It still works, but it should be updated to a uploads.scratch.mit.edu image link in case Scratch gets rid of all images hosted on cnd2.

**The new format for profile picture images using uploads is https://uploads.scratch.mit.edu/users/avatars/USERID.png**

**Comment by Accio1** [comment]
URGENT label because it could possibly break a large portion of the site if not fixed. I will do research about this and then submit a PR to fix this within the next day or two.

**Comment by Accio1** [comment]
To do before I submit the PR:

- [ ] Switch the URL for both curators and mangers inside the JS used to generate the page
- [ ] Ensure that the default PFP works correctly (Scratch was having issues with that recently)
- [ ] Ensure that all file types display correctly (PNG, JPG, GIF)
    - [ ] Ensure that images are sized correctly (including gif images)
    - [ ] PNG images should be transparent, not white in the background

**Comment by leahcimto** [comment]
> @leahcimto Do you have a source of where you found out that cdn2 was switched to uploads?

@Accio1 I am looking into more evedence, but the best I can find right now is right clicking images and going to their URL. I also found that if you want the image size in the URL, you can simply replace the cnd2 part with uploads, making the link look like https://uploads.scratch.mit.edu/get_image/user/USERID_50x50.png
