### ISSUE TITLE
New Issue/Bug Report Templates

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#50]
Before going forward with the site overhaul, I was thinking that it would be a good idea to create new or update old issue templates, as well as create new pull request templates. This needs some discussion before I start to work on it.

For issue templates, I was thinking:
**Bug Template**
Assignees: Accio1
Labels: bug
Title: Bug:

Categories:
- Describe the bug
- Steps to reproduce
- How big of an impact does this have

**Feature Template**
Assignees: Accio1
Labels: enhancement, needs-discussion
Title: Feature Request:

Categories:
- Describe the feature in detail
- Why is this feature needed (If it is related to an issue, link the issue)
- Possible alternatives for this feature

**Other Issue**
Assignees: Accio1
Labels: none
Title: Other:

Categories:
none

And for pull request templates, I was thinking:
**Feature Addition/Bug Fix Template**
Categories:
- Describe what this PR adds/changes
- What issue was resolved? (Please don't submit major PRs unless they resolve an open issue)
- How was this tested?

**Change To List of Forum Helpers Template**
- What does this change? (Does it add a new Forum Helper? Does it change a biography? Does it promote a user from curator to manager?)
- Where did you get this change from? (If changing or adding a biography, link where the user requested the change/addition)

The problem with Pull Request Templates is that there is no way to add labels or titles or assignees to them like there is with issue templates. @leahcimto Would you be opposed to using Github Actions Labeler? https://github.com/actions/labeler to automatically label issues depending on what file was changed. I have tried it out on a private test repository and it seems to work as it should.

**Comment by leahcimto** [comment]
@Accio1 I think there should also be a “List of Forum Helpers” option for adding someone, changing a bio, etc. I would also like to be assigned to that if you wind up making it.

**Comment by Accio1** [comment]
@leahcimto yes I mentioned that in the issue but forgot to bold it

**Comment by leahcimto** [comment]
> The problem with Pull Request Templates is that there is no way to add labels or titles or assignees to them like there is with issue templates. @leahcimto Would you be opposed to using Github Actions Labeler? https://github.com/actions/labeler to automatically label issues depending on what file was changed. I have tried it out on a private test repository and it seems to work as it should.
I think that would be fine. I use it on other projects and it works.
