### ISSUE TITLE
Idea: Use Vercel

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#52]
I think that we should use [Vercel](https://vercel.com) for our pull requests, mainly for the preview option it offers. All that would need to be done would be to configure it to this repository [here](https://github.com/apps/vercel). After configuring it to this website, it will tell you to make a Vercel account, type the URL of this repository, and then finally deploy it. Then, whenever a pull request is submitted it will give you a link to the preview. This will help us avoid bugs and let us catch bugs before merging things into the master branch. Does anyone else think this would be a good idea?

**Comment by Accio1** [comment]
I'll look into using this or similar services, as I agree that it would be useful.

**Comment by jeffalo** [comment]
vercel is also fast like sonic. highly recommended. it also has some automatic building tools, but keep in mind you won't be able to keep the current github.io domain
