### ISSUE TITLE
Bug: Pull request templates don't work

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#54]
**Describe the bug**
Pull request templates don't work

**To Reproduce**
Create a pull request, observe that there are no templates to choose from and no default template.

**Expected behavior**
There should be a selection of templates to choose from and they should have pre filled descriptions.

**Comment by leahcimto** [comment]
CR

**Comment by leahcimto** [comment]
@Accio1 That is so strange. It looks like everything is correct from looking at [this.](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

**Comment by leahcimto** [comment]
Closing as #101 was merged
