### ISSUE TITLE
Site Overhaul: Fix CSS

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#56]
Currently, this site uses a variety of CSS styles for its various parts. For example, different fonts, inconsistent CSS, etc.

In order to make the site more visually appealing, and make future development easier, the following need to be changed to make styles consistent across the site.

### CSS Formating
- [x] **As often as possible, CSS should be located in sytlesheets, not as inline CSS.**
This keeps things neat and organized

- [x] **No duplicate CSS**
There should not be more than one line of CSS that does the same thing to the same class. Redundant CSS should be removed.

- [x] **CSS class names should follow a specific format:**

page_description
Page should be the name of the page with the first letter lowercase. This is followed by an underscore and then a descriptive title of what the class refers to in lowercase

The following should be used as the page name for each class
Main page/homepage- home
List of Forum Helpers- forumhelpers
Header- nav
Footer- footer
Quotes- quotes
eg. home_title, forumhelpers_name, forumhelpers_bio, forumhelpers_pfp, nav_title, foot_link
     - [ ] If a style is used throughout multiple pages (not in the header or footer), then the page name should be "all"

Do not change class or ID names for each block in the list of Forum Helpers page (Do not change FHP.js).

- [x] **Class vs ID**
Classes should be used to refer to an overall component that has one style. IDs should be used if changes are needed to specific parts of a class. Eg. If you had a group of boxes that look the same but are different colours, then all of the boxes would have the same class, which would determine shape, size, etc. IDs would be used to give the boxes different colours.

### Styles
**Fonts**:
- [x] Always use sans serif. Font families for text should be: 
Header: Montserrat, Arial, sans-serif. Montserrat should be obtained from Google Fonts here: https://fonts.google.com/specimen/Montserrat?category=Sans+Serif
Page content: Arial, sans-serif

**Colours**
- [x] Stick with the current colours
- [x] Text should be black

### Other Changes to Styling
- [x] Try to get the headers on the list of Forum Helpers page to stand out more
- [ ] Change link styling (open for discussion @MTM828 feel free to talk about new link colours and transitions here!)

@leahcimto I know that you had expressed an interest in working on this. Do you still want to work on it? 

Also, these changes still need discussion. The points above are just my ideas, feel free to suggest changes or improvements. Once we have a final copy, then this issue can start to be worked on.

### Steps System
Step One: Rename all classes to match the format listed above
Step Two: Remove all inline CSS and convert it to CSS in a stylesheet
Step Three: Add additional CSS (eg. change fonts, etc.)
Step Four: Remove duplicate or unneeded CSS (This step will require extensive testing in order to make sure that no necessary CSS has been removed)

**Comment by leahcimto** [comment]
> @leahcimto I know that you had expressed an interest in working on this. Do you still want to work on it?
Yup, I will get to working on it as soon as I can.

**Comment by Accio1** [comment]
Great! Is there anything you want to change/discuss about the points listed above?

**Comment by leahcimto** [comment]
Yes actually, I would like to ask what you mean by the "class names" because I don't work with CSS a lot and wondering where they go in the stylesheet. Could you give me an example?

**Comment by Accio1** [comment]
Class names are used to identify certain parts of a page/site. 

Inline, they look like this: <h1 class="Home_title">The Forum Helpers</h1>
In a stylesheet, they look like this: .Home_title
The period indicates that is the class that is being referred to.

This website has a pretty good demonstration of what classes are and how to use them: https://www.w3schools.com/html/html_classes.asp

**Comment by leahcimto** [comment]
I see. Thanks for telling me!

**Comment by Accio1** [comment]
You're welcome! I don't know why the first example isn't working. Just quote it to see the actual code.

**Comment by leahcimto** [comment]
Also, for the Montserrat font are we going to use [regular 400](https://fonts.google.com/specimen/Montserrat?category=Sans+Serif&preview.text=The%20Forum%20Helpers.&preview.text_type=custom&sidebar.open=true&selection.family=Montserrat)?

**Comment by Accio1** [comment]
Yes

**Comment by leahcimto** [comment]
One last thing; should I edit the existing stylesheet or start from scratch?

**Comment by Accio1** [comment]
I know that over the summer I was working on redoing the CSS for a site that I was working on (still haven't finished it :P) and I found it helpful to just restart the stylesheet. Then you aren't trying to merge old and new code together. It is up to you though. Just make sure to try to follow the same indenting style that is currently used.

**Comment by leahcimto** [comment]
Ok, I think I will redo it from scratch. I'll start editing it!

**Comment by leahcimto** [comment]
When you say the text should be black, does that include the text in the navbar?

**Comment by Accio1** [comment]
No, I forgot about the nav text. Navbar and footer text should stay white.

**Comment by leahcimto** [comment]
@Accio1 I created a draft pull request here: #57. Please share what you think should be changed.

**Comment by MTM828** [comment]
On it!

**Comment by leahcimto** [comment]
@Accio1, would you like me to make sure all of the div classes match up with the stylesheet?

**Comment by Accio1** [comment]
@leahcimto I'm going to do a full review today. That will include me checking all of the points that I have listed above.

**Comment by MTM828** [comment]
Looks like I'm too late... :P

**Comment by leahcimto** [comment]
@Accio1 Part one created at #58

**Comment by leahcimto** [comment]
@Accio1 could you please review #58?

**Comment by Accio1** [comment]
@leahcimto yes, I will work on that now. I apologize for not getting to it earlier, as I was very busy this week.

**Comment by leahcimto** [comment]
That's fine!

**Comment by leahcimto** [comment]
Part 2 in progress.

**Comment by leahcimto** [comment]
Part 2 created at #62

**Comment by Accio1** [comment]
@leahcimto Part 2 has been merged. Part 3 focuses on adding/changing CSS so that it is more up to date with how the site should look. The changes to be made are listed under the "Styles" header above.

**Comment by leahcimto** [comment]
On it

**Comment by leahcimto** [comment]
@Accio1 Sorry for the wait, the PR should be up by tomorrow.

**Comment by Accio1** [comment]
> @Accio1 Sorry for the wait, the PR should be up by tomorrow.

No worries, take your time

**Comment by leahcimto** [comment]
@Accio1 Could you elaborate on T"ry to get the headers on the list of Forum Helpers page to stand out more"?

**Comment by Accio1** [comment]
@leahcimto how does this look? Do you think it stands out too much?
![image](https://user-images.githubusercontent.com/48496940/106688144-8de71500-659b-11eb-8c57-d3fefc1f0613.png)

**Comment by leahcimto** [comment]
@Accio1 I think that looks ok.

**Comment by Accio1** [comment]
@leahcimto okay,
adding the following code to forumhelpers_subheaders, 
margin-right: 20px;
background: #31ACBA;
padding: 10px;
border-radius: 10px;

and the following code to hr should work:
margin-right: 20px;

**Comment by leahcimto** [comment]
@Accio1 PR up at #71

**Comment by Accio1** [comment]
> @Accio1 PR up at #71

@leahcimto Fantastic! I just merged it. At this point, all that is left is step 4, which is getting rid of duplicate/unneeded CSS.

**Comment by leahcimto** [comment]
@Accio1 Part 4 created at #73

**Comment by Accio1** [comment]
After part 4 is merged, these are the next steps:

- Fix headers and footers to work better on mobile
    - The footer shouldn't change much, it should just get taller as needed to display the text without it overlapping.
    - The header might have to be converted into a dropdown on mobile devices because there isn't enough space for all the links.
    - Related issue: #64 

- Add credits page
    - Now that the stylesheet is done being worked on, there won't be any merge conflicts when the CSS for a credits page is added.
    - Related issue: #36 

- Add statuses to the Forum Helpers List.
    - For example: post count, indicate if they helped develop the website, if they are on the Scratch Team, etc.
    - Related issues: #31 #36 #65

**Comment by Accio1** [comment]
@leahcimto thank you so much for all of your help! This issue can now be closed as it was resolved by #73

**Comment by leahcimto** [comment]
Yay! Thanks for reviewing the PRs!
