### ISSUE TITLE
Integrate Actions Labeller

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#59]
Github Actions Labeller  https://github.com/actions/labeler is a GitHub Action that will automatically label Pull Requests based on which files they change. 

To do this, a workflow.yml file needs to be set up, as well as a labeler.yml file.

In the labeler.yml file, the following labels will be added to PRs based on what they change

- Any changes- unreviewed
- Changes to managers.json or curators.json- Forum Helpers List
- Changes to .github folder or README.md- documentation

Somewhat related to #54

**Comment by leahcimto** [comment]
Support, this would make things more organized.
