### ISSUE TITLE
Feature Request: Update Front Page

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#61]
**Is your feature request related to a problem?**
Yes. The problem is that the application process for the forum helper studio has changed a lot in the past few hours. The grading system was abolished, and other things are still being discussed. The front page should be updated to reflect the new changes.

**Describe alternatives you've considered**
Err.. not really any, as this fixes the front page showing false information.

**Additional context**
Labels: High-Prio, needs-discussion

CC: @Accio1

**Comment by Accio1** [comment]
As there is still ongoing discussion in the Manager studio about this new change, requirements, etc. I am marking this a blocked until everything is officially changed. Once the new process has been implemented and the description has been changed to reflect the new process, then this issue will become unblocked so that the front page can be updated.

**Comment by leahcimto** [comment]
After getting more information, it looks like applicants still fill out the application form, but a manager simply accepts or rejects, no grading needed.

**Comment by Accio1** [comment]
There are still a few pending suggestions in the manager studio, so I'm going to leave this as blocked for now.

**Comment by Accio1** [comment]
@leahcimto I have unblocked this since it seems like the grading process has been finalized. Feel free to submit a PR now if you want to.

**Comment by leahcimto** [comment]
In progress

**Comment by leahcimto** [comment]
Nevermind, I will do this after the inline CSS is merged so there are no merging conflicts.

**Comment by leahcimto** [comment]
I will do this in the next few days
