### ISSUE TITLE
Feature Request: Pending Curators To Be Added

### ISSUE THREAD

**Issue by leahcimto** [theforumhelpers/theforumhelpers.github.io#63]
With the new application system, more users have been getting in a lot quicker, meaning that there are a few applicants that need to be added to the list:

A checkbox indicates that a bio was provided. Bios must be submitted before 4:00 PM EST today (Jan 23)

- [x]  dogsmakemehappy (id: 17609915)
- [x]  garnetluvcookie (id: 56239390)
- [x] Jeffalo (id: 34018398)
- [x]  scratchykit5743 (id: 39136554)
- [X]  -Charon- (id: 41409105)
- [x]  ScratchCatHELLO (id: 25888082)
- [x] chxrrycola-- (id: 70687323)
- [x] mybearworld (id: 62325737)
- [x] 9cjames1 (id: 26089328)

In progress (as of Jan 28, 7:16 PM EST)

**Comment by leahcimto** [comment]
-Charon- bio: Howdy, I'm Charon! You can find me most often in the Questions about Scratch and the Things I'm Reading and Playing forum categories. When I'm not on the forums, I like to make random garbage and play video games like the doofus I am.

**Comment by leahcimto** [comment]
BearSlothCoding bio: Hey, I'm BSC. I used to be active in QaS and Suggestions but now school has left me only posting weird two to three paragraph almost essays no one asked for in TIRAP.

**Comment by leahcimto** [comment]
jeffalo bio: jeffalo

**Comment by leahcimto** [comment]
Remove fdreerf from managers.json 😭

**Comment by leahcimto** [comment]
Move Ihatr and Bluebatstar to managers.json

**Comment by SausageMcSauce** [comment]
> Remove fdreerf from managers.json 😭

I think fdreerf could go in a Former Members section.

**Comment by leahcimto** [comment]
> > Remove fdreerf from managers.json 😭
> 
> I think fdreerf could go in a Former Members section.

@SausageMcSauce We could, but then we would have to include other former members. Maybe "Notable members"?

@Accio1  What are your thoughts on this?

**Comment by leahcimto** [comment]
scratchykit5743 bio:
Hey, I’m scratchykit! I’m an autistic 7th grader who has interest in glee, the New York islanders and cinematic furry memes. I get a lot of 60-second rules and am very anger-prone, so keep note of that.

**Comment by leahcimto** [comment]
Garnetluvcookie bio:
s h r e k

**Comment by leahcimto** [comment]
I have finished updating and will create a PR tomorrow.

**Comment by leahcimto** [comment]
@Accio1 Created at #66

**Comment by Accio1** [comment]
Closed in #66
