### ISSUE TITLE
Bug: margins on mobile

### ISSUE THREAD

**Issue by jeffalo** [theforumhelpers/theforumhelpers.github.io#64]
margins on small devices make reading content impossible

**Comment by Accio1** [comment]
I'm going to work on this on a local copy of this repo. I've added the involved label because this is something that impacts a large portion of the site and may require many changes to fix.

**Comment by jeffalo** [comment]
> I'm going to work on this on a local copy of this repo. I've added the involved label because this is something that impacts a large portion of the site and may require many changes to fix.

uhh I'm not familiar with your codebase, but shouldn't changing a margin amount on smaller screens be pretty simple?

**Comment by Accio1** [comment]
@jeffalo, sorry I should have been more clear. I was more concerned about the header and footer since those are embeds and it is somewhat difficult to resize both the embeds and it's content

**Comment by jeffalo** [comment]
> @jeffalo, sorry I should have been more clear. I was more concerned about the header and footer since those are embeds and it is somewhat difficult to resize both the embeds and it's content

ah that makes more sense 👍 

hey by any chance have you considered rewriting in nuxt, it can generate static sites and vercel supports it. that way the nav could be a Vue component, maybe each user could be a Vue component etc. then you have nice reusable components you can say like `<user name="Jeffalo"/>` instead of messing with iframes and stuff

**Comment by Accio1** [comment]
> > @jeffalo, sorry I should have been more clear. I was more concerned about the header and footer since those are embeds and it is somewhat difficult to resize both the embeds and it's content
> 
> ah that makes more sense 👍
> 
> hey by any chance have you considered rewriting in nuxt, it can generate static sites and vercel supports it. that way the nav could be a Vue component, maybe each user could be a Vue component etc. then you have nice reusable components you can say like `<user name="Jeffalo"/>` instead of messing with iframes and stuff

I'd like this site to have as little dependencies as possible so that it is easy for anyone to contribute to.
