### ISSUE TITLE
Better fonts

### ISSUE THREAD

**Issue by NilsTheBest** [theforumhelpers/theforumhelpers.github.io#7]
We should try to find better fonts for text in different parts of the website. I suggest trying Arial or Arimo. Of course, we can look for other things too. This is just so that we can have a more readable font and make the site look better.

**Comment by Accio1** [comment]
What fonts in particular are you suggesting to be changed? I can read it perfectly fine as is.

**Comment by NilsTheBest** [comment]
I can read it perfectly fine too, it's just that it doesn't really look that "welcoming" if you see what I mean.

I suggest something that looks more like the font Scratch uses for some parts of the front page - Helvetica Neue (it's flat, simple, etc.)

**Comment by Accio1** [comment]
I prefer the way it is now, but if you want to change it, that's fine. Would you prefer it look like the picture I've included?
![Different Fonts](https://user-images.githubusercontent.com/48496940/57818412-cdc7f200-7751-11e9-9e20-169333292f4d.png)

**Comment by NilsTheBest** [comment]
Yeah, that's definitely more pleasant to read. It's more welcoming, "flat" and simple, easy to read ^^

**Comment by Accio1** [comment]
I think what you mean is that the font pictured above a sans-serif font, meaning that there are no extra lines on top or underneath, or on the sides of letters.

Although I prefer serif fonts, I think a good compromise would be having the content be sans-serif, and the header and footer text being serif. (This is the way it's pictured above).

If you approve, I will switch the fonts to the way that it looks above.

**Comment by NilsTheBest** [comment]
Yeah, that does sound like a good idea to me.

**Comment by Accio1** [comment]
Okay, I'll change that now.

**Comment by Accio1** [comment]
This has been implemented, and therefore, this issue can be closed.
