### ISSUE TITLE
Encouraging More Biographies/Inactive Users

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#8]
Right now, the list of Forum Helpers page is very empty, as not many users have provided biographies. I'm wondering if there would be any way to encourage more users to provide biographies. Here are a few of my ideas:

1. Leave comments on the profiles of users without bios.
-We could leave a comment which would say something like this: "Hi there! We are in the process of creating a Forum Helpers website, and one of the pages has a list of Forum Helpers and biographies. Would you be able to provide a biography which we would be able to use on that page?"

2. Use bios from the bio project
-This would be helpful for allowing us to get biographies from users without asking them for one, but there are some downsides, like the biographies might not be up to date, and newer users won't have biographies in that project.

Does anyone have any other ideas and/or thoughts on these ones?

**Comment by NilsTheBest** [comment]
+1

**Comment by Accio1** [comment]
Okay, are you okay with the following comment?

Hi there! We are in the process of creating a Forum Helpers website, and one of the pages has a list of Forum Helpers and biographies. Would you be able to provide a biography which we would be able to use on that page? Random # to avoid spam:

**Comment by Accio1** [comment]
I'll start commenting that on users who haven't provided bios now.

**Comment by Accio1** [comment]
Done

**Comment by Accio1** [comment]
To keep everything consistent, should all biographies be converted to first person, as that's what they are in so far?

**Comment by Accio1** [comment]
> To keep everything consistent, should all biographies be converted to first person, as that's what they are in so far?

@NilsTheBest

**Comment by Nambaseking01** [comment]
I know this wasn't directed at me but you should probably leave it at first person since it is about the person and no one will get suspicions.

**Comment by bybb** [comment]
A lot of the accounts in the list are abandoned and people have moved on to new accounts. A good example is KawaiiCatGirl- who has moved to M1mikyu

**Comment by Accio1** [comment]
Resolved
