### ISSUE TITLE
pls change biography

### ISSUE THREAD

**Issue by CodeGuy92** [theforumhelpers/theforumhelpers.github.io#85]
https://scratch.mit.edu/studios/3688309/comments/#comments-133243932

**Comment by CodeGuy92** [comment]
btw yes its me lanky
dont tell anyone that i made this account

**Comment by Accio1** [comment]
@leahcimto

**Comment by leahcimto** [comment]
@Accio1 Could you merge #83 so we don't run into merge conflicts?

**Comment by Accio1** [comment]
> @Accio1 Could you merge #83 so we don't run into merge conflicts?

For sure. I don't think it would cause merge conflicts since it affects different files, but I'll go ahead just to be sure.

**Comment by leahcimto** [comment]
Thanks

**Comment by Accio1** [comment]
@leahcimto also, if you are going to update this, please also address #82 in the same PR.

**Comment by leahcimto** [comment]
@Accio1 PR up at #86

**Comment by CodeGuy92** [comment]
but dont remove the changes
