### ISSUE TITLE
Bios To Be Added

### ISSUE THREAD

**Issue by Accio1** [theforumhelpers/theforumhelpers.github.io#9]
✔️ MakeTheBrainHappy: https://scratch.mit.edu/users/makethebrainhappy/#comments-57937395
❓ BY147258369: https://scratch.mit.edu/users/BY147258369/#comments-57936161
✔️ XCat: https://scratch.mit.edu/users/XCat/#comments-57942234
✔️ awesome-llama: https://scratch.mit.edu/users/awesome-llama/#comments-57949407
✔️ cs156175: https://scratch.mit.edu/users/cs156175/#comments-57974701
✔️ Abstract-: https://scratch.mit.edu/users/Abstract-/#comments-58015302
✔️ BelieverGirlSun : https://scratch.mit.edu/users/BelieverGirlSun/#comments-57999925
✔️ rainpelt28: https://scratch.mit.edu/users/rainpelt28/#comments-58086506
✔️bbciplayer: https://scratch.mit.edu/users/bbciplayer/#comments-58125514
✔️ jakel181: https://scratch.mit.edu/users/jakel181/#comments-58148825
✔️YubNubEwok : https://scratch.mit.edu/users/YubNubEwok/#comments-58173151
✔️MaximunPokeMaster: https://scratch.mit.edu/users/MaximunPokeMaster/#comments-58460232
✔️jromagnoli: https://scratch.mit.edu/users/jromagnoli/#comments-58471815
✔️Add a note about customhacker being the founder of the studio.
✔️Botcho_Otkho: https://scratch.mit.edu/users/Botcho_Otkho/#comments-58733571
✔️(Changed to 1st person) bigpuppy: https://scratch.mit.edu/users/bigpuppy/#comments-58922596
✔️WolfCat67: https://scratch.mit.edu/users/WolfCat67/#comments-58935448
✔️joshuaho: https://scratch.mit.edu/users/joshuaho/#comments-59012008
✔️-Vuton-: https://scratch.mit.edu/users/-Vuton-/#comments-59099599
✔️DownsGameClub: https://scratch.mit.edu/users/DownsGameClub/#comments-59114580
✔️*Switch Flipped_ to Geonaut
✔️BlueStarPort: https://scratch.mit.edu/users/BlueStarPort/#comments-59407167
✔️54329: https://scratch.mit.edu/users/54329/#comments-59597282
✔️VideoGamerCanInvent: https://scratch.mit.edu/users/VideoGamerCanInvent/#comments-60374085
✔️Add WindOctahedron: https://scratch.mit.edu/users/WindOctahedron/#comments-60913804
✔️BGMead: https://scratch.mit.edu/users/BGMead/#comments-60950080
✔️Nambaseking01: https://scratch.mit.edu/studios/3688309/comments/#comments-67170234
✔️ConfusedBiscuit: https://scratch.mit.edu/studios/3688309/comments/#comments-67193306

**Comment by MakeTheBrainHappy** [comment]
Is this all the code for the website?

**Comment by Accio1** [comment]
> Is this all the code for the website (it looks like it...)?

Yes, I can add you to the organisation if you want.

**Comment by MakeTheBrainHappy** [comment]
Sure, although I haven't programmed many websites before.

**Comment by Nambaseking01** [comment]
It seems like you have to add me and a couple of other Scratchers to the list! I'll give my bio after you respond.

**Comment by Accio1** [comment]
> It seems like you have to add me and a couple of other Scratchers to the list! I'll give my bio after you respond.

https://scratch.mit.edu/studios/3688309/comments/#comments-67136411

**Comment by bybb** [comment]
Bios would be best handled via Jekyll, in my opinion. GitHub pages has native support for Jekyll afterall.

**Comment by Accio1** [comment]
This is no longer needed, because from now on, I will add biographies right away, or track them in an ongoing pull request.
